/**
 * Greenwash Guardian PDF — HTML Template
 *
 * Every page is a fixed 794×1123px div (matching the LCA report pattern).
 * Each page has its own header bar, content area, and absolute-positioned footer.
 * This avoids all Chromium page-break issues with flowing content.
 *
 * Page structure:
 * 1. Cover page (dark)
 * 2. Executive Summary (light)
 * 3–N. One claim per page (light)
 * N+1. Recommendations (light) — may span 2 pages
 * N+2. About/CTA (dark)
 */

// ============================================================================
// TYPES
// ============================================================================

interface ClaimResult {
  claim_text: string;
  claim_context?: string;
  risk_level: 'low' | 'medium' | 'high';
  risk_score: number;
  issue_type: string;
  issue_description: string;
  legislation_name: string;
  legislation_article?: string;
  legislation_jurisdiction: 'uk' | 'eu' | 'both';
  suggestion: string;
  suggested_revision?: string;
}

interface AnalysisResult {
  url: string;
  overall_risk_level: 'low' | 'medium' | 'high';
  overall_risk_score: number;
  summary: string;
  recommendations: string[];
  legislation_applied: Array<{
    name: string;
    jurisdiction: 'uk' | 'eu' | 'both';
    key_requirement: string;
  }>;
  claims: ClaimResult[];
}

// ============================================================================
// HELPERS
// ============================================================================

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function riskColour(level: string): string {
  switch (level) {
    case 'high': return '#dc2626';
    case 'medium': return '#d97706';
    default: return '#16a34a';
  }
}

function riskBg(level: string): string {
  switch (level) {
    case 'high': return '#fef2f2';
    case 'medium': return '#fffbeb';
    default: return '#f0fdf4';
  }
}

function riskBorder(level: string): string {
  switch (level) {
    case 'high': return '#fecaca';
    case 'medium': return '#fde68a';
    default: return '#bbf7d0';
  }
}

function jurisdictionLabel(j: string): string {
  switch (j) {
    case 'uk': return 'UK';
    case 'eu': return 'EU';
    case 'both': return 'UK &amp; EU';
    default: return esc(j);
  }
}

function issueTypeLabel(t: string): string {
  return (t || '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

// ============================================================================
// BRAND
// ============================================================================

const LOGO_URL = 'https://vgbujcuwptvheqijyjbe.supabase.co/storage/v1/object/public/hmac-uploads/uploads/5aedb0b2-3178-4623-b6e3-fc614d5f20ec/1767511420198-2822f942/alkatera_logo-transparent.png';

function logo(height: number, dark = true): string {
  const filter = dark ? '' : 'filter: brightness(0);';
  return `<img src="${LOGO_URL}" alt="alkatera" style="height: ${height}px; width: auto; object-fit: contain; ${filter}" />`;
}

// ============================================================================
// SHARED PAGE CHROME (header bar + footer)
// ============================================================================

function pageHeader(): string {
  return `
    <div style="position: absolute; top: 0; left: 0; right: 0; height: 42px; background: #1c1917; display: flex; align-items: center; justify-content: space-between; padding: 0 48px; z-index: 10;">
      ${logo(16)}
      <span style="font-size: 8px; font-family: 'Fira Code', monospace; color: #ccff00; text-transform: uppercase; letter-spacing: 3px; font-weight: 700;">Greenwash Guardian</span>
    </div>
    <div style="position: absolute; top: 42px; left: 0; right: 0; height: 2px; background: #ccff00; z-index: 10;"></div>`;
}

function pageFooter(pageNum: number, dark = false): string {
  const color = dark ? 'rgba(255,255,255,0.3)' : '#a8a29e';
  const bgColor = dark ? '#1c1917' : '#f5f5f4';
  return `
    <div style="position: absolute; bottom: 0; left: 0; right: 0; z-index: 10; background: ${bgColor}; padding: 0 48px 32px 48px;">
      <div style="display: flex; justify-content: space-between; align-items: center; border-top: 1px solid ${dark ? 'rgba(255,255,255,0.1)' : '#e7e5e4'}; padding-top: 12px;">
        <div style="display: flex; align-items: center; gap: 6px;">
          <span style="font-size: 8px; font-family: 'Fira Code', monospace; color: ${color}; text-transform: uppercase; letter-spacing: 1.5px;">Generated by</span>
          ${logo(12, dark)}
        </div>
        <span style="font-size: 8px; font-family: 'Fira Code', monospace; color: ${color}; text-transform: uppercase; letter-spacing: 1.5px;">hello@alkatera.com</span>
        <span style="font-size: 8px; font-family: 'Fira Code', monospace; color: ${color}; letter-spacing: 1px;">__PAGE_NUM__</span>
      </div>
    </div>`;
}

function sectionHeader(number: string, title: string): string {
  return `
    <div style="display: flex; align-items: baseline; gap: 16px; margin-bottom: 24px; border-bottom: 1px solid rgba(0,0,0,0.08); padding-bottom: 12px;">
      <span style="color: #ccff00; font-family: 'Fira Code', monospace; font-size: 14px; font-weight: 700; letter-spacing: 3px; text-shadow: 0 0 8px rgba(204,255,0,0.3);">${number}</span>
      <h2 style="font-size: 26px; font-family: 'Playfair Display', serif; font-weight: 300; color: #1c1917;">${title}</h2>
    </div>`;
}

// ============================================================================
// COVER PAGE
// ============================================================================

function renderCoverPage(result: AnalysisResult): string {
  const colour = riskColour(result.overall_risk_level);
  const score = result.overall_risk_score;
  const scoreDeg = (score / 100) * 360;
  const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  return `
    <div class="page dark-page" style="justify-content: space-between;">
      <div style="padding-top: 16px;">
        ${logo(44)}
      </div>

      <div>
        <div style="margin-bottom: 48px;">
          <div style="background: #ccff00; color: #0a0a0a; padding: 20px 28px; border-radius: 12px; display: inline-block; transform: rotate(-1deg); margin-bottom: 32px;">
            <div style="font-family: 'Fira Code', monospace; font-weight: 700; font-style: italic; font-size: 20px; letter-spacing: -0.5px;">GREENWASH GUARDIAN</div>
            <div style="font-size: 11px; opacity: 0.6; margin-top: 2px;">Risk Assessment Report</div>
          </div>
          <div style="margin-bottom: 8px;">
            <span style="font-size: 14px; color: #a8a29e; font-family: 'Fira Code', monospace; letter-spacing: 1px;">${esc(result.url.toLowerCase())}</span>
          </div>
          <div style="font-size: 12px; color: #78716c;">${dateStr}</div>
        </div>

        <div style="display: flex; align-items: center; gap: 32px;">
          <div style="width: 140px; height: 140px; border-radius: 50%; background: conic-gradient(${colour} 0deg ${scoreDeg}deg, rgba(255,255,255,0.1) ${scoreDeg}deg 360deg); display: flex; align-items: center; justify-content: center; flex-shrink: 0;">
            <div style="width: 100px; height: 100px; border-radius: 50%; background: #1c1917; display: flex; flex-direction: column; align-items: center; justify-content: center;">
              <div style="font-size: 42px; font-family: 'Playfair Display', serif; font-weight: 700; color: white; line-height: 1;">${score}</div>
              <div style="font-size: 11px; color: #78716c; font-family: 'Fira Code', monospace;">/ 100</div>
            </div>
          </div>
          <div>
            <div style="font-size: 32px; font-family: 'Playfair Display', serif; font-weight: 700; color: ${colour}; margin-bottom: 4px;">${result.overall_risk_level.toUpperCase()} RISK</div>
            <div style="font-size: 13px; color: #a8a29e;">Overall greenwashing risk score</div>
          </div>
        </div>
      </div>

      <div>
        <div style="background: rgba(217,119,6,0.1); border: 1px solid rgba(217,119,6,0.3); border-radius: 8px; padding: 10px 16px; display: flex; gap: 12px; align-items: center; margin-bottom: 20px;">
          <span style="font-size: 8px; font-weight: 700; color: #fbbf24; font-family: 'Fira Code', monospace; letter-spacing: 2px; text-transform: uppercase; white-space: nowrap;">Disclaimer</span>
          <span style="font-size: 9px; color: #a8a29e;">This report provides guidance only and is not legal advice. Consult qualified legal counsel for compliance decisions.</span>
        </div>
        <div style="display: flex; justify-content: space-between; align-items: center; font-size: 9px; font-family: 'Fira Code', monospace; color: rgba(255,255,255,0.25); text-transform: uppercase; letter-spacing: 2px; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 14px;">
          <div style="display: flex; align-items: center; gap: 8px;">
            <span>Generated by</span>
            ${logo(14)}
          </div>
          <div>Greenwash Guardian</div>
        </div>
      </div>
    </div>`;
}

// ============================================================================
// EXECUTIVE SUMMARY PAGE
// ============================================================================

function renderSummaryPage(result: AnalysisResult, pageNum: number): string {
  const highCount = result.claims.filter(c => c.risk_level === 'high').length;
  const medCount = result.claims.filter(c => c.risk_level === 'medium').length;
  const lowCount = result.claims.filter(c => c.risk_level === 'low').length;

  const legislationHtml = result.legislation_applied.map(l => `
    <div style="display: flex; align-items: center; gap: 10px; padding: 7px 0; border-bottom: 1px solid #f0f0ef;">
      <span style="display: inline-block; background: #ccff00; color: #0a0a0a; font-size: 7px; font-weight: 700; font-family: 'Fira Code', monospace; padding: 2px 7px; border-radius: 3px; letter-spacing: 1px; flex-shrink: 0;">${jurisdictionLabel(l.jurisdiction)}</span>
      <span style="font-size: 10px; color: #44403c;">${esc(l.name)}</span>
    </div>`).join('');

  return `
    <div class="page light-page">
      ${pageHeader()}

      <div class="page-body">
        ${sectionHeader('01', 'Executive Summary')}

        <div style="display: flex; gap: 14px; margin-bottom: 22px;">
          <div style="flex: 1; background: white; border: 1px solid #fecaca; border-radius: 10px; padding: 16px; display: flex; align-items: center; gap: 14px;">
            <div style="font-size: 36px; font-family: 'Playfair Display', serif; font-weight: 700; color: #dc2626; line-height: 1;">${highCount}</div>
            <div>
              <div style="font-size: 9px; font-family: 'Fira Code', monospace; color: #dc2626; text-transform: uppercase; letter-spacing: 2px; font-weight: 700;">High</div>
              <div style="font-size: 8px; color: #a8a29e; text-transform: uppercase; letter-spacing: 1px;">Risk</div>
            </div>
          </div>
          <div style="flex: 1; background: white; border: 1px solid #fde68a; border-radius: 10px; padding: 16px; display: flex; align-items: center; gap: 14px;">
            <div style="font-size: 36px; font-family: 'Playfair Display', serif; font-weight: 700; color: #d97706; line-height: 1;">${medCount}</div>
            <div>
              <div style="font-size: 9px; font-family: 'Fira Code', monospace; color: #d97706; text-transform: uppercase; letter-spacing: 2px; font-weight: 700;">Medium</div>
              <div style="font-size: 8px; color: #a8a29e; text-transform: uppercase; letter-spacing: 1px;">Risk</div>
            </div>
          </div>
          <div style="flex: 1; background: white; border: 1px solid #bbf7d0; border-radius: 10px; padding: 16px; display: flex; align-items: center; gap: 14px;">
            <div style="font-size: 36px; font-family: 'Playfair Display', serif; font-weight: 700; color: #16a34a; line-height: 1;">${lowCount}</div>
            <div>
              <div style="font-size: 9px; font-family: 'Fira Code', monospace; color: #16a34a; text-transform: uppercase; letter-spacing: 2px; font-weight: 700;">Low</div>
              <div style="font-size: 8px; color: #a8a29e; text-transform: uppercase; letter-spacing: 1px;">Risk</div>
            </div>
          </div>
        </div>

        <div style="background: white; border: 1px solid #e7e5e4; border-radius: 10px; padding: 20px; margin-bottom: 22px;">
          <div style="font-size: 9px; font-family: 'Fira Code', monospace; color: #78716c; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">Summary</div>
          <p style="font-size: 11px; line-height: 1.75; color: #44403c;">${esc(result.summary)}</p>
        </div>

        <div style="background: white; border: 1px solid #e7e5e4; border-radius: 10px; padding: 20px;">
          <div style="font-size: 9px; font-family: 'Fira Code', monospace; color: #78716c; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 8px;">Legislation Applied</div>
          ${legislationHtml}
        </div>
      </div>

      ${pageFooter(pageNum)}
    </div>`;
}

// ============================================================================
// CLAIM PAGE (one claim per page)
// ============================================================================

function renderClaimPage(claim: ClaimResult, index: number, pageNum: number): string {
  const colour = riskColour(claim.risk_level);
  const bg = riskBg(claim.risk_level);
  const border = riskBorder(claim.risk_level);
  const legText = `${claim.legislation_name}${claim.legislation_article ? ` (${claim.legislation_article})` : ''}`;

  return `
    <div class="page light-page">
      ${pageHeader()}

      <div class="page-body">
        <!-- Card -->
        <div style="border-radius: 10px; overflow: hidden; border: 1px solid #e7e5e4; box-shadow: 0 1px 3px rgba(0,0,0,0.04);">
          <!-- Card header -->
          <div style="background: ${colour}; padding: 10px 18px; display: flex; align-items: center; gap: 10px;">
            <span style="font-size: 11px; font-family: 'Fira Code', monospace; font-weight: 700; color: rgba(255,255,255,0.4); letter-spacing: 2px;">${String(index).padStart(2, '0')}</span>
            <span style="background: rgba(255,255,255,0.2); border: 1px solid rgba(255,255,255,0.3); color: white; font-size: 7px; font-weight: 700; padding: 2px 8px; border-radius: 10px; text-transform: uppercase; letter-spacing: 1px;">${claim.risk_level.toUpperCase()}</span>
            <span style="font-size: 9px; color: rgba(255,255,255,0.8); font-family: 'Fira Code', monospace;">Score: ${claim.risk_score}/100</span>
            <span style="font-size: 9px; color: rgba(255,255,255,0.7); margin-left: auto;">${esc(issueTypeLabel(claim.issue_type))}</span>
          </div>

          <!-- Card body -->
          <div style="padding: 18px; background: white;">
            <div style="font-size: 12px; font-weight: 600; color: #1c1917; line-height: 1.5; margin-bottom: 14px; padding-left: 14px; border-left: 3px solid ${colour};">
              &ldquo;${esc(claim.claim_text)}&rdquo;
            </div>

            <div style="margin-bottom: 14px;">
              <div style="font-size: 8px; font-family: 'Fira Code', monospace; color: #78716c; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 5px;">Issue Description</div>
              <p style="font-size: 10px; color: #57534e; line-height: 1.7;">${esc(claim.issue_description)}</p>
            </div>

            <div style="display: flex; align-items: flex-start; gap: 8px; margin-bottom: 14px;">
              <span style="display: inline-block; background: #ccff00; color: #0a0a0a; font-size: 7px; font-weight: 700; font-family: 'Fira Code', monospace; padding: 2px 7px; border-radius: 3px; letter-spacing: 1px; flex-shrink: 0; margin-top: 1px;">${jurisdictionLabel(claim.legislation_jurisdiction)}</span>
              <span style="font-size: 9px; color: #78716c; line-height: 1.5;">${esc(legText)}</span>
            </div>

            <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 12px 14px; margin-bottom: ${claim.suggested_revision ? '10px' : '0'};">
              <div style="font-size: 8px; font-family: 'Fira Code', monospace; color: #16a34a; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 5px; font-weight: 700;">Suggestion</div>
              <p style="font-size: 9px; color: #166534; line-height: 1.6;">${esc(claim.suggestion)}</p>
            </div>

            ${claim.suggested_revision ? `
            <div style="background: ${bg}; border: 1px solid ${border}; border-radius: 8px; padding: 12px 14px;">
              <div style="font-size: 8px; font-family: 'Fira Code', monospace; color: #78716c; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 5px; font-weight: 600;">Suggested Revision</div>
              <p style="font-size: 9px; color: #57534e; line-height: 1.6; font-style: italic;">&ldquo;${esc(claim.suggested_revision)}&rdquo;</p>
            </div>` : ''}
          </div>
        </div>
      </div>

      ${pageFooter(pageNum)}
    </div>`;
}

// ============================================================================
// RECOMMENDATIONS PAGE
// ============================================================================

function renderRecommendationsPage(recs: string[], pageNum: number): string {
  const recsHtml = recs.map((r, i) => `
    <div style="display: flex; gap: 12px; margin-bottom: 14px;">
      <div style="width: 24px; height: 24px; background: #ccff00; border-radius: 50%; display: flex; align-items: center; justify-content: center; flex-shrink: 0;">
        <span style="font-size: 10px; font-weight: 700; color: #0a0a0a; font-family: 'Fira Code', monospace;">${i + 1}</span>
      </div>
      <p style="font-size: 10px; color: #44403c; line-height: 1.7; flex: 1; padding-top: 3px;">${esc(r)}</p>
    </div>`).join('');

  return `
    <div class="page light-page">
      ${pageHeader()}

      <div class="page-body">
        ${sectionHeader('03', 'Recommendations')}
        ${recsHtml}
      </div>

      ${pageFooter(pageNum)}
    </div>`;
}

// ============================================================================
// ABOUT PAGE (dark)
// ============================================================================

function renderAboutPage(pageNum: number): string {
  const services = [
    { name: 'Greenwash Guardian', desc: 'AI-powered compliance scanning against UK and EU anti-greenwashing legislation' },
    { name: 'Life Cycle Assessments', desc: 'Product-level environmental impact analysis with ISO 14044 methodology' },
    { name: 'Sustainability Reporting', desc: 'Automated reports for stakeholders, investors, and B Corp certification' },
    { name: 'Supply Chain Tracking', desc: 'Monitor and improve environmental performance across your supplier network' },
    { name: 'Carbon Footprint Management', desc: 'Scope 1, 2, and 3 emissions tracking with reduction roadmaps' },
  ];

  const servicesHtml = services.map(s => `
    <div style="display: flex; gap: 10px; margin-bottom: 10px;">
      <div style="width: 6px; height: 6px; background: #ccff00; border-radius: 50%; margin-top: 6px; flex-shrink: 0;"></div>
      <div>
        <span style="font-size: 10px; font-weight: 600; color: white;">${esc(s.name)}:</span>
        <span style="font-size: 10px; color: #a8a29e;"> ${esc(s.desc)}</span>
      </div>
    </div>`).join('');

  return `
    <div class="page dark-page" style="justify-content: center;">
      <div style="padding: 0 48px;">
        <div style="margin-bottom: 28px;">
          ${logo(44)}
        </div>

        <p style="font-size: 14px; color: #d6d3d1; line-height: 1.8; max-width: 540px; margin-bottom: 36px;">
          alka<strong style="font-weight: 700;">tera</strong> is the sustainability platform built for the drinks industry. We help breweries, distilleries, and wineries measure, manage, and communicate their environmental impact with confidence.
        </p>

        <div style="font-size: 9px; font-family: 'Fira Code', monospace; color: #ccff00; text-transform: uppercase; letter-spacing: 3px; margin-bottom: 14px;">Our Services</div>
        ${servicesHtml}

        <div style="background: #ccff00; border-radius: 12px; padding: 28px 32px; text-align: center; margin-top: 36px;">
          <div style="font-size: 20px; font-family: 'Playfair Display', serif; font-weight: 700; color: #0a0a0a; margin-bottom: 8px;">Want unlimited scans and full compliance tracking?</div>
          <div style="font-size: 13px; color: #0a0a0a;">Get started at alka<strong>tera</strong>.com</div>
          <div style="font-size: 11px; font-weight: 700; color: #0a0a0a; margin-top: 6px; font-family: 'Fira Code', monospace;">hello@alkatera.com</div>
        </div>
      </div>

      ${pageFooter(pageNum, true)}
    </div>`;
}

// ============================================================================
// MAIN RENDERER
// ============================================================================

export function renderGreenwashHtml(result: AnalysisResult): string {
  const pages: string[] = [];

  // Page 1: Cover
  pages.push(renderCoverPage(result));

  // Page 2: Executive Summary
  pages.push(renderSummaryPage(result, 2));

  // Pages 3–N: One claim per page
  result.claims.forEach((claim, i) => {
    pages.push(renderClaimPage(claim, i + 1, 3 + i));
  });

  // Recommendations page
  const recsPageNum = 3 + result.claims.length;
  if (result.recommendations?.length > 0) {
    pages.push(renderRecommendationsPage(result.recommendations, recsPageNum));
  }

  // About page
  const aboutPageNum = recsPageNum + (result.recommendations?.length > 0 ? 1 : 0);
  pages.push(renderAboutPage(aboutPageNum));

  // Replace __PAGE_NUM__ placeholders with sequential numbers
  let counter = 0;
  const pagesHtml = pages.join('\n').replace(/__PAGE_NUM__/g, () => String(++counter));

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Greenwash Guardian Report</title>

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@300;700&family=Fira+Code:wght@400;700&display=swap" rel="stylesheet" />

  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: 'Inter', system-ui, -apple-system, sans-serif;
      -webkit-font-smoothing: antialiased;
      background: white;
      color: #1c1917;
    }

    @page { size: A4; margin: 0; }

    .page {
      width: 794px;
      height: 1123px;
      position: relative;
      display: flex;
      flex-direction: column;
      padding: 48px;
      padding-bottom: 80px;
      overflow: hidden;
      page-break-after: always;
      break-after: page;
    }

    .page:last-child { page-break-after: auto; break-after: auto; }

    .dark-page { background: #1c1917; color: white; }
    .light-page { background: #f5f5f4; color: #1c1917; }

    /* Content area below header bar */
    .page-body {
      margin-top: 16px;
      flex: 1;
    }

    @media print {
      body { background: white; }
      .page { box-shadow: none; margin: 0; }
    }
  </style>
</head>
<body>
  ${pagesHtml}
</body>
</html>`;
}
