'use client';

import { useState, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { BookOpen, ChevronDown, Download, Minus, Plus } from 'lucide-react';

// ─── Types ──────────────────────────────────────────────────────────────────

interface MethodologyItem {
  capital: string;
  metric_key: string;
  label: string;
  proxy_value: number;
  unit: string;
  source: string;
}

interface ImpactValuationMethodologyProps {
  methodologyItems: MethodologyItem[];
  proxyVersion: string | null;
  calculatedAt: string | null;
  methodologyLoading: boolean;
  orgName: string;
  selectedYear: number;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="text-sm font-semibold text-foreground mt-6 mb-2">{children}</h3>
  );
}

function FormulaBox({ children }: { children: React.ReactNode }) {
  return (
    <div className="my-3 rounded-md border-l-4 border-[#ccff00] bg-[#ccff00]/5 dark:bg-[#ccff00]/10 px-4 py-3">
      <p className="text-sm font-mono font-semibold text-foreground">{children}</p>
    </div>
  );
}

function MetricDetailTable({
  rows,
}: {
  rows: { label: string; value: string }[];
}) {
  return (
    <div className="my-2 rounded-md border">
      <Table>
        <TableBody>
          {rows.map((row) => (
            <TableRow key={row.label}>
              <TableCell className="font-medium text-muted-foreground w-[140px] py-2 text-xs">
                {row.label}
              </TableCell>
              <TableCell className="py-2 text-xs">{row.value}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}

function generateMethodologyStatement(
  orgName: string,
  year: number,
  version: string,
  calculatedAt: string,
  items: MethodologyItem[]
): string {
  const capitalGroupLabels: Record<string, string> = {
    natural: 'NATURAL CAPITAL',
    human: 'HUMAN CAPITAL',
    social: 'SOCIAL CAPITAL',
    governance: 'GOVERNANCE CAPITAL',
  };
  const capitalOrder = ['natural', 'human', 'social', 'governance'];

  let text = `alkatera Impact Valuation Methodology Statement\n`;
  text += `Organisation: ${orgName}\n`;
  text += `Reporting Year: ${year}\n`;
  text += `Proxy Version: ${version}\n`;
  text += `Calculated: ${new Date(calculatedAt).toLocaleDateString('en-GB')}\n\n`;

  for (const capital of capitalOrder) {
    const capitalItems = items.filter((i) => i.capital === capital);
    if (capitalItems.length === 0) continue;
    text += `${capitalGroupLabels[capital]}\n`;
    for (const item of capitalItems) {
      text += `- ${item.label}: £${Number(item.proxy_value).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 4 })} ${item.unit} — ${item.source}\n`;
    }
    text += '\n';
  }

  text += `This methodology statement was generated by alkatera. All proxy values\n`;
  text += `are independently sourced and versioned. Calculations are deterministic.\n`;

  return text;
}

// ─── Main component ─────────────────────────────────────────────────────────

export function ImpactValuationMethodology({
  methodologyItems,
  proxyVersion,
  calculatedAt,
  methodologyLoading,
  orgName,
  selectedYear,
}: ImpactValuationMethodologyProps) {
  const [open, setOpen] = useState(false);

  const capitalGroupLabels: Record<string, string> = {
    natural: 'Natural Capital',
    human: 'Human Capital',
    social: 'Social Capital',
    governance: 'Governance Capital',
  };
  const capitalOrder = ['natural', 'human', 'social', 'governance'];

  const handleDownload = useCallback(() => {
    if (!proxyVersion || !calculatedAt || methodologyItems.length === 0) return;

    const text = generateMethodologyStatement(
      orgName,
      selectedYear,
      proxyVersion,
      calculatedAt,
      methodologyItems
    );

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `alkatera-impact-valuation-methodology-${selectedYear}-v${proxyVersion}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [proxyVersion, calculatedAt, methodologyItems, orgName, selectedYear]);

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <Card>
        <CollapsibleTrigger asChild>
          <CardHeader className="cursor-pointer hover:bg-muted/50 transition-colors">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <BookOpen className="h-5 w-5 text-muted-foreground" />
                <div>
                  <CardTitle className="text-base">Understanding Impact Valuation</CardTitle>
                  {proxyVersion && calculatedAt && (
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Methodology, proxy values, and data sources · v{proxyVersion}
                    </p>
                  )}
                </div>
              </div>
              <ChevronDown
                className={`h-4 w-4 text-muted-foreground transition-transform ${
                  open ? 'rotate-180' : ''
                }`}
              />
            </div>
          </CardHeader>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <CardContent className="pt-0 space-y-4">
            {/* ── What is Impact Valuation? ──────────────────────────────── */}
            <SectionHeading>What is Impact Valuation?</SectionHeading>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Impact Valuation translates your organisation&apos;s environmental and social
              performance into monetary values using independently-sourced proxy prices
              (shadow prices). This makes it possible to understand the true cost or
              benefit of your operations in financial terms — the kind of language
              boards, investors, and retail buyers understand.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              The core formula is straightforward:
            </p>
            <FormulaBox>Impact Value (£) = Raw Metric Quantity × Proxy Value (£ per unit)</FormulaBox>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Every number traces back to either a raw input value from your
              organisation&apos;s data or a published proxy value. No AI or machine learning
              is used in the calculations — they are purely deterministic. AI is used only
              to generate optional narrative summaries.
            </p>

            {/* ── How the Net Impact is Calculated ───────────────────────── */}
            <SectionHeading>How the Net Impact is Calculated</SectionHeading>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Not all impacts are equal. Some represent <strong>costs</strong> to society
              (environmental harm), while others represent <strong>benefits</strong> (social
              value created). The Net Impact subtracts costs from benefits:
            </p>
            <FormulaBox>Net Impact = Benefits − Costs</FormulaBox>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 my-3">
              <div className="rounded-md border border-emerald-200 dark:border-emerald-800 bg-emerald-50/50 dark:bg-emerald-950/20 p-3">
                <div className="flex items-center gap-2 mb-1">
                  <Plus className="h-3.5 w-3.5 text-emerald-600" />
                  <span className="text-xs font-semibold text-emerald-700 dark:text-emerald-400">Benefits</span>
                </div>
                <p className="text-xs text-muted-foreground">
                  Employee training, wellbeing, volunteering, charitable giving, local
                  supply chain spend, governance quality
                </p>
              </div>
              <div className="rounded-md border border-red-200 dark:border-red-800 bg-red-50/50 dark:bg-red-950/20 p-3">
                <div className="flex items-center gap-2 mb-1">
                  <Minus className="h-3.5 w-3.5 text-red-600" />
                  <span className="text-xs font-semibold text-red-700 dark:text-red-400">Costs</span>
                </div>
                <p className="text-xs text-muted-foreground">
                  Carbon emissions, water consumption, land use, waste to landfill,
                  living wage gap
                </p>
              </div>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              A positive Net Impact means your organisation creates more social value than
              environmental cost. A negative Net Impact means environmental costs outweigh
              the social benefits measured so far — this is common when data coverage is
              still building.
            </p>

            {/* ── Natural Capital (Costs) ────────────────────────────────── */}
            <SectionHeading>Detailed Metric Breakdowns</SectionHeading>

            <Accordion type="multiple" className="w-full">
              {/* ── Natural Capital ── */}
              <AccordionItem value="natural">
                <AccordionTrigger className="text-sm font-semibold">
                  Natural Capital (Costs)
                </AccordionTrigger>
                <AccordionContent className="space-y-4">
                  {/* Carbon */}
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-2">
                    Carbon Emissions (GHG)
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total greenhouse gas emissions across Scope 1, 2, and 3' },
                      { label: 'Unit', value: 'Tonnes of CO₂ equivalent (tCO₂e)' },
                      { label: 'Proxy Value', value: '£259.00 per tCO₂e' },
                      { label: 'Source', value: 'Defra 2024 shadow carbon price (central estimate)' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    The UK Government publishes carbon values for policy appraisal via the
                    Green Book. These use a <strong>target-consistent approach</strong> (Marginal
                    Abatement Cost method): rather than estimating damage, they ask
                    &ldquo;what will it cost to abate this tonne to meet the UK&apos;s net zero target?&rdquo;
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    The series is anchored on a 2040 reference point of £326/tCO₂e (2020 prices)
                    with 1.5% annual real growth. The 2024 central value is £256, rising to £260
                    in 2025. alkatera uses a rounded central figure of <strong>£259</strong>. Low
                    and high estimates (±50%) are published but alkatera uses the central estimate
                    for conservatism.
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed italic">
                    Example: 150 tCO₂e × £259 = £38,850
                  </p>

                  {/* Water */}
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Water Consumption
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total water consumption, adjusted for geographic scarcity' },
                      { label: 'Unit', value: 'm³ world-equivalent (scarcity-weighted)' },
                      { label: 'Proxy Value', value: '£0.90 per m³ world-equivalent' },
                      { label: 'Source', value: 'Defra 2024 water abstraction charge proxy (AWARE weighted)' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Raw water volume alone is misleading. The <strong>AWARE methodology</strong> (Available
                    Water Remaining), developed by the UNEP-SETAC Life Cycle Initiative and compliant
                    with ISO 14046, answers: &ldquo;what is the potential to deprive another user —
                    human or ecosystem — when consuming water in this area?&rdquo;
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    AWARE factors range from 0.1 (very water-abundant) to 100 (extremely
                    water-scarce). Each facility&apos;s water use is multiplied by its country&apos;s
                    AWARE factor to produce m³ world-equivalent. A Scottish distillery (factor ~0.5)
                    uses 1,000 m³ = 500 m³ world-eq. A Spanish winery (factor ~3.0) uses
                    1,000 m³ = 3,000 m³ world-eq.
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed italic">
                    Example: 5,000 m³ × AWARE 1.5 = 7,500 m³ world-eq × £0.90 = £6,750
                  </p>

                  {/* Land Use */}
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Land Use
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total land occupation attributable to products, including supply chain' },
                      { label: 'Unit', value: 'Hectares per year (ha/yr)' },
                      { label: 'Proxy Value', value: '£183.00 per ha/yr' },
                      { label: 'Source', value: 'Capitals Coalition (Natural Capital Protocol)' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Land use impact is captured at the material/ingredient level within each
                    product&apos;s LCA (m²a — square metres per year). This covers both ingredients
                    and packaging, accounting for the full supply chain. Per-unit land footprint
                    is multiplied by production volume and converted to hectares (÷ 10,000).
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed italic">
                    Example: 50 ha/yr × £183 = £9,150
                  </p>

                  {/* Waste */}
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Waste to Landfill
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total waste sent to landfill from operational facilities' },
                      { label: 'Unit', value: 'Tonnes' },
                      { label: 'Proxy Value', value: '£102.00 per tonne' },
                      { label: 'Source', value: 'UK landfill tax standard rate 2024 (£102.10/t, rounded)' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Based directly on the UK Landfill Tax, introduced in 1996 to incentivise
                    diversion from landfill. The standard rate has risen from £7/tonne in 1996
                    to £103.70 in 2024-25, reaching £130.75 from April 2026. Only waste with
                    treatment method &lsquo;landfill&rsquo; is included — recycled, composted, or
                    energy-recovered waste is excluded.
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed italic">
                    Example: 25 tonnes × £102 = £2,550
                  </p>
                </AccordionContent>
              </AccordionItem>

              {/* ── Human Capital ── */}
              <AccordionItem value="human">
                <AccordionTrigger className="text-sm font-semibold">
                  Human Capital (Mixed)
                </AccordionTrigger>
                <AccordionContent className="space-y-4">
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-2">
                    Living Wage Gap <Badge variant="outline" className="ml-2 text-[10px] text-red-600 border-red-200">Cost</Badge>
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Monetary gap between actual pay and the real living wage' },
                      { label: 'Unit', value: '£ per £1 gap per year' },
                      { label: 'Proxy Value', value: '£1.00 (direct monetary value)' },
                      { label: 'Source', value: 'Direct monetary value' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    This metric represents a cost — the shortfall between what your organisation
                    pays and the real living wage. A larger gap means a greater negative social
                    impact. Closing the gap directly reduces this cost.
                  </p>

                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Employee Training <Badge variant="outline" className="ml-2 text-[10px] text-emerald-600 border-emerald-200">Benefit</Badge>
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total employee training hours delivered' },
                      { label: 'Proxy Value', value: '£13.00 per hour' },
                      { label: 'Source', value: 'CIPD Learning at Work Survey 2023' },
                    ]}
                  />

                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Employee Wellbeing <Badge variant="outline" className="ml-2 text-[10px] text-emerald-600 border-emerald-200">Benefit</Badge>
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Employee wellbeing score improvement' },
                      { label: 'Proxy Value', value: '£420.00 per 1-point improvement' },
                      { label: 'Source', value: 'Wellbeing Economy Alliance / HACT proxy' },
                    ]}
                  />
                </AccordionContent>
              </AccordionItem>

              {/* ── Social Capital ── */}
              <AccordionItem value="social">
                <AccordionTrigger className="text-sm font-semibold">
                  Social Capital (Benefits)
                </AccordionTrigger>
                <AccordionContent className="space-y-4">
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-2">
                    Volunteering Hours
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total employee volunteering hours' },
                      { label: 'Proxy Value', value: '£28.00 per hour' },
                      { label: 'Source', value: 'NCVO UK Voluntary Sector 2023 (median wage proxy)' },
                    ]}
                  />

                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Charitable Giving
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total cash donations' },
                      { label: 'Proxy Value', value: '£1.00 per £1 donated' },
                      { label: 'Source', value: 'Direct monetary value' },
                    ]}
                  />

                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-4">
                    Local Supply Chain Spend
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Total local procurement spend' },
                      { label: 'Proxy Value', value: '£0.63 per £1 local spend (LM3 coefficient)' },
                      { label: 'Source', value: 'NEF Local Multiplier 3 (LM3) model' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    The LM3 coefficient measures how much additional economic activity is generated
                    locally for each pound spent with local suppliers, based on the New Economics
                    Foundation&apos;s Local Multiplier methodology.
                  </p>
                </AccordionContent>
              </AccordionItem>

              {/* ── Governance Capital ── */}
              <AccordionItem value="governance">
                <AccordionTrigger className="text-sm font-semibold">
                  Governance Capital (Benefits)
                </AccordionTrigger>
                <AccordionContent className="space-y-4">
                  <h4 className="text-xs font-semibold text-foreground uppercase tracking-wide mt-2">
                    Governance Quality
                  </h4>
                  <MetricDetailTable
                    rows={[
                      { label: 'Measures', value: 'Overall governance score (0–100)' },
                      { label: 'Proxy Value', value: '£1,250.00 per 1-point score' },
                      { label: 'Source', value: 'Social Value Bank SROI proxy' },
                    ]}
                  />
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    Good governance reduces risk, improves stakeholder trust, and enables
                    better decision-making. The proxy value is derived from the Social Value
                    Bank&apos;s Social Return on Investment (SROI) framework.
                  </p>
                </AccordionContent>
              </AccordionItem>

              {/* ── Data Coverage & Confidence ── */}
              <AccordionItem value="confidence">
                <AccordionTrigger className="text-sm font-semibold">
                  Data Coverage &amp; Confidence Levels
                </AccordionTrigger>
                <AccordionContent className="space-y-3">
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    alkatera tracks how many of the 11 total metrics have real data and
                    assigns a confidence level:
                  </p>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Badge className="bg-emerald-100 text-emerald-800 dark:bg-emerald-900/50 dark:text-emerald-300 text-[10px]">High</Badge>
                      <span className="text-xs text-muted-foreground">≥80% of metrics (9+ of 11)</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge className="bg-amber-100 text-amber-800 dark:bg-amber-900/50 dark:text-amber-300 text-[10px]">Medium</Badge>
                      <span className="text-xs text-muted-foreground">50–79% (5–8 of 11)</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge className="bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400 text-[10px]">Low</Badge>
                      <span className="text-xs text-muted-foreground">&lt;50% (fewer than 5 of 11)</span>
                    </div>
                  </div>
                  <p className="text-xs text-muted-foreground leading-relaxed mt-2">
                    <strong>Zero vs &ldquo;No data&rdquo;:</strong> If a metric has data entered and the
                    value is zero, it shows as £0 (e.g. no waste to landfill — a positive outcome).
                    If no data has been entered, it shows as &ldquo;No data&rdquo; and is excluded
                    from the calculation. This prevents organisations appearing to have zero impact
                    simply because data hasn&apos;t been entered yet.
                  </p>
                </AccordionContent>
              </AccordionItem>

              {/* ── Key Principles ── */}
              <AccordionItem value="principles">
                <AccordionTrigger className="text-sm font-semibold">
                  Key Methodological Principles
                </AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-2">
                    {[
                      { title: 'Transparency', desc: 'Every proxy value is cited with its authoritative source and version number.' },
                      { title: 'Determinism', desc: 'No AI or machine learning in the calculations — pure multiplication of raw data × proxy values.' },
                      { title: 'Auditability', desc: 'Every calculation stores a complete input snapshot for independent verification.' },
                      { title: 'Conservatism', desc: 'Where sources provide a range, the central (not high) estimate is used.' },
                      { title: 'Geographic sensitivity', desc: 'Water consumption is adjusted for local water stress using AWARE factors.' },
                      { title: 'Completeness', desc: 'Carbon includes all scopes (1, 2, 3). Land use covers the full supply chain.' },
                    ].map((p) => (
                      <div key={p.title} className="flex gap-2">
                        <span className="text-xs font-semibold text-foreground whitespace-nowrap">{p.title}.</span>
                        <span className="text-xs text-muted-foreground">{p.desc}</span>
                      </div>
                    ))}
                  </div>
                </AccordionContent>
              </AccordionItem>

              {/* ── FAQ ── */}
              <AccordionItem value="faq">
                <AccordionTrigger className="text-sm font-semibold">
                  Frequently Asked Questions
                </AccordionTrigger>
                <AccordionContent className="space-y-4">
                  {[
                    {
                      q: 'Why is my net impact negative?',
                      a: 'A negative Net Impact means your environmental costs (Natural Capital) currently outweigh the social benefits measured. This is common when data coverage is still building — as you add Human, Social, and Governance data, the benefits side will grow. It can also genuinely reflect that environmental impact reduction should be a priority.',
                    },
                    {
                      q: 'Why does carbon dominate my Natural Capital cost?',
                      a: 'The shadow carbon price (£259/tCO₂e) reflects the full societal cost of emissions as estimated by UK Government economists — including climate adaptation, health impacts, and economic disruption. Even modest emission volumes produce significant monetary values. This is intentional.',
                    },
                    {
                      q: 'What is a shadow price?',
                      a: 'A shadow price is an estimated monetary value for something without a direct market price. Economists estimate the long-term societal cost of, say, one tonne of CO₂. Shadow prices are widely used in government cost-benefit analysis and environmental economics.',
                    },
                    {
                      q: 'Can I compare my values with other organisations?',
                      a: 'Yes, but ensure like-for-like: same reporting year, similar data coverage, and same proxy value version. The confidence level indicator helps assess comparability.',
                    },
                    {
                      q: 'How often are proxy values updated?',
                      a: 'Periodically, when authoritative sources publish new figures. Historical calculations are preserved on their original proxy version, so past valuations are never retrospectively changed.',
                    },
                    {
                      q: 'Why is my water value different from my water bill?',
                      a: 'The proxy value (£0.90/m³ world-eq) reflects the environmental cost of water abstraction including ecosystem impact, not the commercial price from your utility. The AWARE scarcity-weighting further adjusts for where water is consumed.',
                    },
                  ].map((faq) => (
                    <div key={faq.q}>
                      <p className="text-xs font-semibold text-foreground">{faq.q}</p>
                      <p className="text-xs text-muted-foreground leading-relaxed mt-1">
                        {faq.a}
                      </p>
                    </div>
                  ))}
                </AccordionContent>
              </AccordionItem>
            </Accordion>

            {/* ── Proxy Values Table ─────────────────────────────────────── */}
            <SectionHeading>Current Proxy Values</SectionHeading>

            {methodologyLoading ? (
              <div className="space-y-2">
                <Skeleton className="h-8 w-full" />
                <Skeleton className="h-8 w-full" />
                <Skeleton className="h-8 w-full" />
              </div>
            ) : methodologyItems.length > 0 ? (
              <div className="space-y-4">
                {capitalOrder.map((capital) => {
                  const items = methodologyItems.filter((i) => i.capital === capital);
                  if (items.length === 0) return null;
                  return (
                    <div key={capital}>
                      <h4 className="text-xs font-semibold mb-1.5">
                        {capitalGroupLabels[capital]}
                      </h4>
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead className="text-xs">Metric</TableHead>
                            <TableHead className="text-right text-xs">Proxy Value</TableHead>
                            <TableHead className="text-xs">Unit</TableHead>
                            <TableHead className="text-xs">Source</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {items.map((item) => (
                            <TableRow key={item.metric_key}>
                              <TableCell className="font-medium text-xs">
                                {item.label}
                              </TableCell>
                              <TableCell className="text-right tabular-nums text-xs">
                                £{Number(item.proxy_value).toLocaleString('en-GB', {
                                  minimumFractionDigits: 2,
                                  maximumFractionDigits: 4,
                                })}
                              </TableCell>
                              <TableCell className="text-muted-foreground text-xs">
                                {item.unit}
                              </TableCell>
                              <TableCell className="text-muted-foreground text-xs">
                                {item.source}
                              </TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                  );
                })}
              </div>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                No methodology data available for this calculation.
              </p>
            )}

            {/* Footer */}
            {proxyVersion && (
              <p className="text-xs text-muted-foreground border-t pt-4">
                Proxy values are versioned. The values shown reflect version {proxyVersion}.
                When proxy values are updated, existing historical calculations remain tied
                to the version used at the time.
              </p>
            )}

            <Button
              variant="outline"
              size="sm"
              onClick={handleDownload}
              disabled={!proxyVersion || methodologyItems.length === 0}
              className="gap-2"
            >
              <Download className="h-4 w-4" />
              Download Methodology Statement
            </Button>
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}
