import type { FrameworkContentDef } from './types';

// EcoVadis sustainability rating - 21 criteria across 4 themes. Paraphrased from
// the public methodology (Policies / Actions / Results lens); no proprietary
// EcoVadis questionnaire wording reproduced. Auto-evidence targets the Results
// pillar (alkatera holds metrics, not signed policy narratives), so a probe
// partly satisfies a criterion but never replaces the policy/action evidence.
export const ECOVADIS: FrameworkContentDef = {
  code: 'ecovadis',
  label: 'EcoVadis',
  frameworkId: 'ccc5d243-19c5-4205-aeb6-bd495ce444d9',
  reqIdPrefix: 'a0ec0d15',
  categoryOrder: ['Environment', 'Labour & Human Rights', 'Ethics', 'Sustainable Procurement'],
  requirements: [
    { code: 'ECOVADIS-ENV-01', name: 'Energy use & greenhouse gas emissions', category: 'Environment', summary: 'How you manage energy and your carbon footprint across Scopes 1-3: the policy commitment, reduction measures, and the measured trend over time.', evidence: ['GHG inventory with Scope 1-2-3 breakdown', 'Climate/energy policy plus a quantified target (e.g. SBTi)', 'Year-on-year energy and emissions KPIs'], pitfalls: ['An emissions figure with no methodology or boundary', 'A target with no baseline year or numeric goal'], probe: 'emissionsTarget' },
    { code: 'ECOVADIS-ENV-02', name: 'Water management', category: 'Environment', summary: 'How you monitor and reduce water consumption and protect water quality: policy, efficiency actions, and reported consumption.', evidence: ['Water consumption metrics with a trend', 'A water-efficiency initiative', 'Water intensity per unit of production'], pitfalls: ['An absolute volume but no intensity or trend'], probe: 'waterData' },
    { code: 'ECOVADIS-ENV-03', name: 'Biodiversity & land use', category: 'Environment', summary: 'Impacts on ecosystems, habitats and land from operations and sourcing: biodiversity policy, protective/restorative actions, and monitored outcomes.', evidence: ['Biodiversity or land-use policy', 'Habitat protection or restoration projects', 'Metrics on protected land area'], pitfalls: ["Generic 'we care about nature' statements with no specific action"], probe: null },
    { code: 'ECOVADIS-ENV-04', name: 'Local & accidental pollution', category: 'Environment', summary: 'Control of air, soil and water pollution and prevention of spills/accidental releases: prevention policy, controls, and incident results.', evidence: ['Pollution prevention / spill response procedure', 'Air or effluent monitoring at facilities', 'Record of pollution incidents'], pitfalls: ['No incident-tracking process'], probe: 'wasteData' },
    { code: 'ECOVADIS-ENV-05', name: 'Materials, chemicals & waste', category: 'Environment', summary: 'Responsible use of materials and chemicals and how waste is reduced, reused or recycled: policy, circularity actions, and waste/recycling metrics.', evidence: ['Waste / circular-economy policy', 'Recycling, reuse or chemical-substitution initiatives', 'Total waste, hazardous waste and recycling-rate KPIs'], pitfalls: ['Reporting only total waste without a recycling rate'], probe: 'wasteData' },
    { code: 'ECOVADIS-ENV-06', name: 'Product use impacts', category: 'Environment', summary: 'The environmental footprint of products in the customer-use phase and efforts to design lower-impact products.', evidence: ['Eco-design or product-stewardship policy', 'Product reformulation or efficiency improvements', 'Product life-cycle assessment covering the use phase'], pitfalls: ['Treating product impact as identical to operational impact'], probe: 'productLca' },
    { code: 'ECOVADIS-ENV-07', name: 'Product end-of-life', category: 'Environment', summary: 'How products and packaging are managed at disposal - recyclability, take-back and end-of-life design.', evidence: ['Packaging or end-of-life / EPR policy', 'Recyclable-packaging redesign or take-back scheme', 'Share of recyclable packaging'], pitfalls: ["Claiming 'recyclable' with no figure for the proportion it applies to"], probe: 'productLcaEol' },
    { code: 'ECOVADIS-LAB-01', name: 'Employee health & safety', category: 'Labour & Human Rights', summary: 'How you protect worker health and safety on site: the H&S policy, prevention/training measures, and incident-rate results.', evidence: ['Health & safety policy or ISO 45001', 'Safety training and risk assessments', 'Accident frequency/severity KPIs'], pitfalls: ['No injury-rate data to verify the record'], probe: null },
    { code: 'ECOVADIS-LAB-02', name: 'Working conditions', category: 'Labour & Human Rights', summary: 'Pay, working hours, benefits and overall job quality: policy, wage/benefit actions, and results such as living-wage coverage.', evidence: ['Remuneration / working-hours policy', 'Living-wage or benefits programme', 'Living-wage coverage rate and benefits metrics'], pitfalls: ["Stating wages 'meet legal minimum' without addressing living wage"], probe: 'compensation' },
    { code: 'ECOVADIS-LAB-03', name: 'Social dialogue & employee engagement', category: 'Labour & Human Rights', summary: 'Worker representation, collective bargaining and engagement: policy on freedom of association, dialogue actions, and engagement results.', evidence: ['Freedom-of-association policy', 'Works council, union recognition or employee surveys', 'Engagement-survey scores'], probe: null },
    { code: 'ECOVADIS-LAB-04', name: 'Career management & training', category: 'Labour & Human Rights', summary: 'Investment in employee skills, training and development: policy, development actions, and training-hour/coverage results.', evidence: ['Training & development policy', 'Skills or apprenticeship programmes', 'Average training hours per employee'], pitfalls: ['Listing courses offered but no participation data'], probe: 'training' },
    { code: 'ECOVADIS-LAB-05', name: 'Child labour, forced labour & trafficking', category: 'Labour & Human Rights', summary: 'Safeguards against child labour, forced labour and trafficking in operations and supply chain: prohibition policy, due-diligence, and monitoring.', evidence: ['Policy prohibiting child and forced labour', 'Age-verification and supply-chain due-diligence', 'Audit coverage or modern-slavery statement'], pitfalls: ['A policy that ignores the supply chain'], probe: null },
    { code: 'ECOVADIS-LAB-06', name: 'Diversity, discrimination & harassment', category: 'Labour & Human Rights', summary: 'Anti-discrimination protections and promotion of diversity, equity and inclusion: policy, grievance/inclusion actions, and diversity metrics.', evidence: ['Anti-discrimination / DEI policy', 'Grievance channel and DEI initiatives', 'Workforce diversity metrics (gender balance, pay gap)'], pitfalls: ['A DEI statement with no demographic data'], probe: 'workforceDemographics' },
    { code: 'ECOVADIS-LAB-07', name: "External stakeholders' human rights", category: 'Labour & Human Rights', summary: 'Respect for the human rights of communities and people outside the workforce affected by operations.', evidence: ['Human-rights policy referencing affected communities', 'Community impact assessments or grievance mechanisms', 'Records of community engagement'], pitfalls: ['Human-rights policy scoped only to employees'], probe: 'community' },
    { code: 'ECOVADIS-LAB-08', name: 'Fundamental human rights', category: 'Labour & Human Rights', summary: 'Your overarching commitment to internationally recognised human rights and your due-diligence process.', evidence: ['Human-rights policy aligned to the UN Guiding Principles', 'Human-rights due-diligence / risk-mapping', 'Disclosure of salient risks and mitigation'], probe: 'governancePolicies' },
    { code: 'ECOVADIS-ETH-01', name: 'Anti-corruption & bribery', category: 'Ethics', summary: 'Prevention of corruption, bribery and fraud: policy, control/training actions, and outcomes such as incidents and audit coverage.', evidence: ['Anti-corruption policy and code of conduct', 'Anti-corruption training and third-party due-diligence', 'Records of corruption incidents and % of staff trained'], pitfalls: ['Policy with no training rollout'], probe: 'governanceEthics' },
    { code: 'ECOVADIS-ETH-02', name: 'Anticompetitive practices', category: 'Ethics', summary: 'Safeguards against anti-competitive behaviour such as price-fixing and abuse of market position: policy, training, and results.', evidence: ['Fair-competition / antitrust policy', 'Competition-law training', 'Record of any anti-competitive actions'], pitfalls: ['Assuming this only applies to large firms'], probe: 'governancePolicies' },
    { code: 'ECOVADIS-ETH-03', name: 'Responsible information management', category: 'Ethics', summary: 'Protection of data, privacy and information security, including customer and employee data: policy, security actions, and breach results.', evidence: ['Data-protection / privacy policy (e.g. GDPR-aligned)', 'Security measures or ISO 27001', 'Record of data breaches and remediation'], pitfalls: ['No breach-notification process'], probe: 'governancePolicies' },
    { code: 'ECOVADIS-ETH-04', name: 'Responsible influence & advocacy', category: 'Ethics', summary: 'Transparency and integrity in lobbying, political contributions and industry-association influence.', evidence: ['Responsible lobbying policy', 'Disclosure of trade-association memberships and positions', 'Records of political contributions and lobbying spend'], pitfalls: ['Treating lobbying as N/A while holding active association memberships'], probe: 'governanceEthics' },
    { code: 'ECOVADIS-PROC-01', name: "Suppliers' environmental practices", category: 'Sustainable Procurement', summary: 'How you integrate environmental criteria into sourcing and monitor suppliers: procurement policy, assessment/engagement actions, and coverage.', evidence: ['Sustainable procurement policy + supplier code of conduct', 'Supplier environmental assessments or audits', '% of spend/suppliers assessed on environmental criteria'], pitfalls: ['A supplier code that is signed but never verified'], probe: 'supplierEsg' },
    { code: 'ECOVADIS-PROC-02', name: "Suppliers' social practices", category: 'Sustainable Procurement', summary: 'How you integrate social and human-rights criteria into sourcing and monitor suppliers: procurement policy, assessment actions, and coverage.', evidence: ['Supplier code covering labour and human rights', 'Social audits, SAQs or supplier capacity-building', '% of suppliers/spend assessed on social criteria'], pitfalls: ['Assessing only Tier-1 suppliers when risk sits deeper'], probe: 'supplierEsg' },
  ],
};
