import type { FrameworkContentDef } from './types';

// ISO 14001:2015 — Environmental Management Systems. Requirements paraphrased
// from the public Annex SL clause structure (clauses 4–10); no copyrighted
// standard text reproduced.
export const ISO14001: FrameworkContentDef = {
  code: 'iso14001',
  label: 'ISO 14001',
  frameworkId: '98d8efe8-9956-4461-967c-af2b2b838300',
  reqIdPrefix: 'a0e14001',
  categoryOrder: [
    'Context of the organisation',
    'Leadership',
    'Planning',
    'Support',
    'Operation',
    'Performance evaluation',
    'Improvement',
  ],
  requirements: [
    { code: 'ISO14001-4.1', name: 'Understand your organisation and its context', category: 'Context of the organisation', summary: 'Identify the internal and external issues (commercial, regulatory, environmental conditions) that affect what your EMS needs to achieve.', evidence: ['Context analysis / PESTLE register', 'SWOT linked to environmental issues', 'Documented review of external conditions (water stress, climate, local regulation)'], pitfalls: ['Treating this as a one-off rather than a reviewed input'], probe: 'facilities' },
    { code: 'ISO14001-4.2', name: 'Identify interested parties and their needs', category: 'Context of the organisation', summary: 'Determine who has a stake in your environmental performance (regulators, customers, community, employees) and which of their needs you treat as obligations.', evidence: ['Interested-parties register with needs/expectations', 'Mapping of which expectations become compliance obligations'], pitfalls: ['Listing parties but never capturing what each one expects'], probe: 'community' },
    { code: 'ISO14001-4.3', name: 'Define the scope of the EMS', category: 'Context of the organisation', summary: 'Set and document the boundaries of the EMS — which sites, activities, products and services it applies to.', evidence: ['Documented EMS scope statement listing sites, activities and products in/out of scope'], pitfalls: ['Excluding sites or activities the organisation actually controls'], probe: 'facilities' },
    { code: 'ISO14001-4.4', name: 'Establish and maintain the EMS', category: 'Context of the organisation', summary: 'Set up, run and continually improve the environmental management system and the processes within it.', evidence: ['EMS manual / process map', 'Evidence of interacting processes (Plan-Do-Check-Act)'], pitfalls: ['An EMS that does not reflect how the organisation actually operates'], probe: 'governancePolicies' },
    { code: 'ISO14001-5.1', name: 'Top management leadership and commitment', category: 'Leadership', summary: 'Senior leaders take accountability for the EMS, integrate it into business processes and provide the resources for it to work.', evidence: ['Board/leadership minutes referencing the EMS', 'Resource allocation records', 'Signed commitment statement'], pitfalls: ['Delegating all EMS ownership to one person with no leadership involvement'], probe: null },
    { code: 'ISO14001-5.2', name: 'Environmental policy', category: 'Leadership', summary: 'Maintain a documented environmental policy that fits the organisation, commits to protecting the environment, meeting obligations and continual improvement, and is communicated.', evidence: ['Signed environmental policy', 'Evidence it is published internally and available externally'], pitfalls: ['A generic policy with no commitment to legal compliance or continual improvement'], probe: 'governancePolicies' },
    { code: 'ISO14001-5.3', name: 'Roles, responsibilities and authorities', category: 'Leadership', summary: 'Top management assigns and communicates who is responsible for which EMS duties.', evidence: ['Responsibility matrix / RACI', 'Role descriptions covering EMS duties'], pitfalls: ['Assigning responsibility without the authority to act'], probe: null },
    { code: 'ISO14001-6.1.1', name: 'Plan to address risks and opportunities', category: 'Planning', summary: 'Decide how you will identify and handle the risks and opportunities tied to your environmental aspects, compliance obligations and context.', evidence: ['Risk and opportunity register tied to context and parties', 'Planning methodology note'], pitfalls: ['Listing risks with no planned actions or owners'], probe: 'reductionPlan' },
    { code: 'ISO14001-6.1.2', name: 'Identify environmental aspects and significance', category: 'Planning', summary: 'Determine the environmental aspects of your activities, products and services that you can control or influence, and decide which are significant.', evidence: ['Environmental aspects/impacts register with significance scoring', 'Lifecycle-perspective evidence'], pitfalls: ['Ignoring indirect/value-chain aspects', 'Undocumented significance criteria'], probe: 'productLca' },
    { code: 'ISO14001-6.1.3', name: 'Determine compliance obligations', category: 'Planning', summary: 'Identify the legal requirements and other obligations relevant to your environmental aspects and how they apply to you.', evidence: ['Legal and other requirements register', 'Method for tracking regulatory changes'], pitfalls: ['A static legal register that is never updated'], probe: null },
    { code: 'ISO14001-6.1.4', name: 'Plan actions for aspects, obligations and risks', category: 'Planning', summary: 'Plan actions to address significant aspects, compliance obligations and risks, and integrate them into your processes.', evidence: ['Action plans linked to specific aspects/obligations', 'Effectiveness review records'], pitfalls: ['Actions disconnected from the significance and risk analysis'], probe: 'reductionPlan' },
    { code: 'ISO14001-6.2', name: 'Environmental objectives and plans to meet them', category: 'Planning', summary: 'Set measurable environmental objectives consistent with the policy, and plan what will be done, by whom, by when, and how results are evaluated.', evidence: ['Documented objectives with metrics, baselines and target dates', 'Action plans with owners and resources'], pitfalls: ['Objectives that are not measurable or not linked to significant aspects'], probe: 'emissionsTarget' },
    { code: 'ISO14001-7.1', name: 'Resources for the EMS', category: 'Support', summary: 'Determine and provide the people, infrastructure and resources needed to run and improve the EMS.', evidence: ['Budget/resource plans for EMS activities', 'Staffing and monitoring-equipment records'], pitfalls: ['Approving objectives without funding the resources to deliver them'], probe: null },
    { code: 'ISO14001-7.2', name: 'Competence', category: 'Support', summary: 'Ensure people whose work affects environmental performance are competent, and act to close competence gaps.', evidence: ['Competence matrix', 'Training records and certificates', 'Evidence of training effectiveness'], pitfalls: ['Recording attendance but never verifying competence'], probe: 'training' },
    { code: 'ISO14001-7.3', name: 'Awareness', category: 'Support', summary: 'Make sure staff are aware of the environmental policy, significant aspects, their EMS contribution and the consequences of not conforming.', evidence: ['Induction/awareness material', 'Toolbox talks', 'Staff acknowledgements'], pitfalls: ['Confusing one policy email with genuine, role-relevant awareness'], probe: 'training' },
    { code: 'ISO14001-7.4', name: 'Communication', category: 'Support', summary: 'Plan and carry out internal and external communications relevant to the EMS — what, when, with whom and how.', evidence: ['Communication plan/matrix', 'Records of internal updates and external enquiry responses'], pitfalls: ['No process for handling and recording external environmental enquiries'], probe: null },
    { code: 'ISO14001-7.5', name: 'Documented information', category: 'Support', summary: 'Create, control and maintain the documents and records the EMS requires, including version, access and retention controls.', evidence: ['Document control procedure', 'Version-controlled document register', 'Records retention schedule'], pitfalls: ['Uncontrolled documents with no owner, version or review date'], probe: 'governancePolicies' },
    { code: 'ISO14001-8.1', name: 'Operational planning and control', category: 'Operation', summary: 'Establish and control the operational processes needed to meet EMS requirements, including a lifecycle perspective and control over outsourced processes.', evidence: ['Operating procedures for significant aspects', 'Control criteria', 'Lifecycle, procurement and outsourced-process controls'], pitfalls: ['Forgetting lifecycle stages and outsourced/contractor activities'], probe: 'energyData' },
    { code: 'ISO14001-8.2', name: 'Emergency preparedness and response', category: 'Operation', summary: 'Identify potential environmental emergencies and prepare, test and review planned responses.', evidence: ['Emergency response procedures', 'Spill/incident drill records', 'Post-incident review notes'], pitfalls: ['A written plan that is never tested or updated after drills'], probe: null },
    { code: 'ISO14001-9.1.1', name: 'Monitoring, measurement, analysis, evaluation', category: 'Performance evaluation', summary: 'Decide what environmental performance to monitor and measure, with valid methods, and analyse and evaluate the results.', evidence: ['Monitoring plan listing metrics and methods', 'Calibration records', 'Performance dashboards/analysis'], pitfalls: ['Collecting data but never evaluating it against objectives'], probe: 'metricTrend' },
    { code: 'ISO14001-9.1.2', name: 'Evaluation of compliance', category: 'Performance evaluation', summary: 'Periodically evaluate whether you are meeting your compliance obligations and maintain knowledge of your compliance status.', evidence: ['Compliance evaluation records against the legal register', 'Corrective actions for gaps'], pitfalls: ['Assuming compliance instead of formally evaluating and recording it'], probe: null },
    { code: 'ISO14001-9.2', name: 'Internal audit', category: 'Performance evaluation', summary: 'Run a planned programme of internal audits to check the EMS conforms and is effectively implemented.', evidence: ['Internal audit programme/schedule', 'Auditor competence/independence records', 'Audit reports and findings'], pitfalls: ['Auditors checking their own work', 'Audits with no follow-up'], probe: null },
    { code: 'ISO14001-9.3', name: 'Management review', category: 'Performance evaluation', summary: 'Top management periodically reviews the EMS using defined inputs (performance, audits, compliance, objectives) and records decisions and actions.', evidence: ['Management review minutes', 'Agenda covering required inputs', 'Documented decisions and resource changes'], pitfalls: ['Reviews that skip required inputs or produce no actions'], probe: 'metricTrend' },
    { code: 'ISO14001-10.1', name: 'Improvement (general)', category: 'Improvement', summary: 'Determine opportunities for improvement and act on them to enhance environmental performance.', evidence: ['Improvement opportunity log', 'Trend analysis driving improvements'], pitfalls: ['Treating improvement as only fixing problems, not raising performance'], probe: 'reductionPlan' },
    { code: 'ISO14001-10.2', name: 'Nonconformity and corrective action', category: 'Improvement', summary: 'React to nonconformities, correct them, investigate root cause, take corrective action and check it worked.', evidence: ['Nonconformity / corrective action register', 'Root-cause analysis records', 'Effectiveness verification'], pitfalls: ['Fixing the symptom without root-cause analysis'], probe: null },
    { code: 'ISO14001-10.3', name: 'Continual improvement', category: 'Improvement', summary: 'Continually improve the suitability, adequacy and effectiveness of the EMS to enhance environmental performance over time.', evidence: ['Multi-period performance trends', 'Reviewed objectives showing tightening targets'], pitfalls: ['Static objectives that never get more ambitious'], probe: 'metricTrend' },
  ],
};
