import type { FrameworkContentDef } from './types';

// ISO 50001:2018 - Energy Management Systems. Paraphrased from the public
// Annex SL clause structure (clauses 4-10 incl. the energy-specific planning
// sub-clauses); no copyrighted standard text reproduced.
export const ISO50001: FrameworkContentDef = {
  code: 'iso50001',
  label: 'ISO 50001',
  frameworkId: '53ac5afb-a3b7-4956-a07d-42079798dae7',
  reqIdPrefix: 'a0e50001',
  categoryOrder: [
    'Context of the organisation',
    'Leadership',
    'Planning',
    'Support',
    'Operation',
    'Performance evaluation',
    'Improvement',
  ],
  requirements: [
    { code: 'ISO50001-4.1', name: 'Understand the organisation and its context', category: 'Context of the organisation', summary: 'Identify the internal and external issues that affect the energy management system and your ability to improve energy performance.', evidence: ['Context analysis / SWOT note', 'List of internal/external issues with a review date'], pitfalls: ['Ignoring external drivers like energy prices or regulation'], probe: null },
    { code: 'ISO50001-4.2', name: 'Needs of interested parties (incl. legal requirements)', category: 'Context of the organisation', summary: 'Determine relevant interested parties, which of their needs become requirements, and capture applicable legal and other energy obligations.', evidence: ['Stakeholder register', 'Legal & other requirements register with how each is met'], pitfalls: ['A stale legal register'], probe: 'governancePolicies' },
    { code: 'ISO50001-4.3', name: 'Define the EnMS scope and boundaries', category: 'Context of the organisation', summary: 'Set out what the energy management system covers - facilities, activities and energy types inside its boundaries.', evidence: ['Documented scope statement naming sites/boundaries', 'Rationale for any exclusions'], pitfalls: ['Excluding a significant energy use to make certification easier'], probe: 'facilities' },
    { code: 'ISO50001-4.4', name: 'Establish and maintain the EnMS', category: 'Context of the organisation', summary: 'Put in place an energy management system that continually improves both the system and energy performance.', evidence: ['EnMS manual or process map', 'List of EnMS processes and owners'], pitfalls: ["Documenting processes that don't reflect what staff actually do"], probe: null },
    { code: 'ISO50001-5.1', name: 'Top management leadership and commitment', category: 'Leadership', summary: 'Senior leaders own the EnMS, resource it, integrate energy performance into the business, and back the energy team.', evidence: ['Board/leadership minutes referencing energy performance', 'Resource allocation records'], pitfalls: ['Sign-off with no follow-through on resources'], probe: null },
    { code: 'ISO50001-5.2', name: 'Energy policy', category: 'Leadership', summary: 'Establish a documented energy policy committing to continual energy-performance improvement, legal compliance, and availability of information and resources.', evidence: ['Signed, dated energy policy', 'Evidence it is communicated', 'Commitment to provide information/resources'], pitfalls: ["A template policy that doesn't match the operation"], probe: 'governancePolicies' },
    { code: 'ISO50001-5.3', name: 'Roles, responsibilities and authorities', category: 'Leadership', summary: 'Assign and communicate clear EnMS responsibilities, including who reports on energy performance to top management.', evidence: ['RACI for the energy team', 'Appointment record for the energy management lead'], pitfalls: ['One person with no deputy or authority'], probe: null },
    { code: 'ISO50001-6.1', name: 'Actions to address risks and opportunities', category: 'Planning', summary: 'Identify risks and opportunities from the context and interested parties, and plan actions so the EnMS achieves its results.', evidence: ['Risk & opportunity register tied to context issues', 'Planned actions with owners'], pitfalls: ['Confusing this with health-and-safety risk'], probe: 'reductionPlan' },
    { code: 'ISO50001-6.2', name: 'Objectives, energy targets and planning', category: 'Planning', summary: 'Set energy objectives and measurable energy targets consistent with the policy, and plan how they will be achieved and evaluated.', evidence: ['Documented objectives and targets', 'Action plans with owners, timescales and resources'], pitfalls: ['Targets with no action plan or not aligned to significant energy uses'], probe: 'emissionsTarget' },
    { code: 'ISO50001-6.3', name: 'Energy review', category: 'Planning', summary: 'Carry out and maintain a structured analysis of energy use, identify significant energy uses (SEUs) and the factors affecting them, and find improvement opportunities.', evidence: ['Documented energy review methodology', 'SEU list with the criteria used', 'Register of improvement opportunities'], pitfalls: ['Skipping the SEU step', 'Reviewing once and never updating'], probe: 'energyData' },
    { code: 'ISO50001-6.4', name: 'Energy performance indicators (EnPIs)', category: 'Planning', summary: 'Determine EnPIs that let you measure and demonstrate energy-performance improvement, and review them against the baseline.', evidence: ['Documented EnPIs and how each is calculated', 'Records of EnPI values over time'], pitfalls: ['Using only total consumption, so improvements are masked by production swings'], probe: 'metricTrend' },
    { code: 'ISO50001-6.5', name: 'Energy baseline (EnB)', category: 'Planning', summary: 'Establish energy baselines using a suitable reference period against which energy-performance changes are measured, and maintain them.', evidence: ['Documented baseline period and values', 'Relevant variables/normalisation used'], pitfalls: ['An unrepresentative baseline year', 'Adjusting the baseline without justification'], probe: 'metricTrend' },
    { code: 'ISO50001-6.6', name: 'Planning for collection of energy data', category: 'Planning', summary: 'Define a plan for collecting the energy data needed to manage performance - variables, SEUs, meters and accuracy.', evidence: ['Energy data collection plan', 'List of meters/measurement points and intervals'], pitfalls: ['Relying on annual utility bills only'], probe: 'energyData' },
    { code: 'ISO50001-7.1', name: 'Resources', category: 'Support', summary: 'Determine and provide the people, infrastructure and resources needed to establish, maintain and improve the EnMS.', evidence: ['Approved budget/resource plan for energy work', 'Evidence of metering/monitoring tools provided'], pitfalls: ['Allocating people only, ignoring metering infrastructure'], probe: null },
    { code: 'ISO50001-7.2', name: 'Competence', category: 'Support', summary: 'Ensure people whose work affects energy performance are competent, and keep evidence of this.', evidence: ['Competence matrix', 'Training records and certificates'], pitfalls: ['Generic awareness training counted as competence for technical roles'], probe: 'training' },
    { code: 'ISO50001-7.3', name: 'Awareness', category: 'Support', summary: 'Make sure people under your control are aware of the energy policy, their contribution to energy performance, and the benefits of improvement.', evidence: ['Awareness session records', 'Induction materials covering energy'], pitfalls: ['Treating awareness as identical to competence'], probe: 'training' },
    { code: 'ISO50001-7.4', name: 'Communication', category: 'Support', summary: 'Determine internal and external EnMS communications and provide a way for staff to suggest energy improvements.', evidence: ['Communication plan/matrix', 'A channel for energy improvement suggestions'], pitfalls: ['No mechanism for bottom-up suggestions'], probe: null },
    { code: 'ISO50001-7.5', name: 'Documented information', category: 'Support', summary: 'Create, control and maintain the documented information required, with proper version, access and retention control.', evidence: ['Document control procedure', 'Controlled document register with versions'], pitfalls: ['Uncontrolled spreadsheets nobody can find at audit'], probe: null },
    { code: 'ISO50001-8.1', name: 'Operational planning and control', category: 'Operation', summary: 'Plan, implement and control operations linked to significant energy uses, set operating criteria, and control planned changes.', evidence: ['Operating procedures/criteria for SEUs', 'Maintenance and change-control records'], pitfalls: ['Operating criteria (set-points, limits) not defined'], probe: 'energyData' },
    { code: 'ISO50001-8.2', name: 'Design', category: 'Operation', summary: 'Consider energy-performance improvement and operational control in the design of new or modified facilities, equipment and processes.', evidence: ['Design review checklists including energy criteria', 'Project records showing energy was assessed'], pitfalls: ['Energy considered too late to influence the design'], probe: 'reductionPlan' },
    { code: 'ISO50001-8.3', name: 'Procurement', category: 'Operation', summary: 'Where procurement significantly affects energy performance, set energy criteria for purchases and inform suppliers that energy matters.', evidence: ['Procurement policy with energy criteria', 'Tender/specification documents citing efficiency'], pitfalls: ['Buying on capital cost alone'], probe: 'governancePolicies' },
    { code: 'ISO50001-9.1', name: 'Monitoring & evaluation of energy performance', category: 'Performance evaluation', summary: 'Monitor and measure EnPIs, SEUs, action-plan progress and actual vs expected consumption, and act on significant deviations.', evidence: ['Monitoring plan', 'EnPI/SEU trend records', 'Analysis of actual vs expected energy use'], pitfalls: ['Collecting data but not evaluating it; ignoring deviations'], probe: 'metricTrend' },
    { code: 'ISO50001-9.1c', name: 'Evaluation of compliance with legal requirements', category: 'Performance evaluation', summary: 'Evaluate, at planned intervals, whether you comply with legal and other energy requirements, and keep records.', evidence: ['Compliance evaluation records', 'Updated legal register showing compliance status'], pitfalls: ['Evaluating compliance once and assuming it holds'], probe: null },
    { code: 'ISO50001-9.2', name: 'Internal audit', category: 'Performance evaluation', summary: 'Run internal audits at planned intervals to check the EnMS conforms and is effectively implemented, using competent, impartial auditors.', evidence: ['Internal audit programme/schedule', 'Audit reports with findings'], pitfalls: ['Auditors auditing their own work'], probe: null },
    { code: 'ISO50001-9.3', name: 'Management review', category: 'Performance evaluation', summary: 'Top management reviews the EnMS against defined inputs (energy performance, EnPIs, objectives, actions) and records decisions.', evidence: ['Management review minutes covering required inputs', 'Recorded decisions and actions'], pitfalls: ['Review that skips EnPI performance or objective status'], probe: 'metricTrend' },
    { code: 'ISO50001-10.1', name: 'Nonconformity and corrective action', category: 'Improvement', summary: 'React to nonconformities, correct them, remove their cause through corrective action, and verify the action worked.', evidence: ['Nonconformity/corrective action log', 'Root-cause analyses'], pitfalls: ['Fixing the symptom without root-cause analysis'], probe: null },
    { code: 'ISO50001-10.2', name: 'Continual improvement', category: 'Improvement', summary: 'Continually improve the EnMS and demonstrate continual improvement of energy performance over time.', evidence: ['Trend of EnPIs showing improvement', 'Year-on-year energy performance comparison'], pitfalls: ['Claiming improvement without normalised data'], probe: 'metricTrend' },
  ],
};
