// Pure HTML renderers for the B Corp audit package PDFs. No server-only /
// Supabase imports so these can be unit-tested.

import type { RequirementStatus } from './scoring';

function esc(s: string | null | undefined): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

const BASE_CSS = `
  body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0a0a0a;margin:40px;}
  h1{font-size:22px;margin:0 0 4px;} h2{font-size:16px;margin:24px 0 8px;}
  .muted{color:#525960;font-size:12px;} table{width:100%;border-collapse:collapse;margin-top:8px;}
  th,td{text-align:left;font-size:12px;padding:6px 8px;border-bottom:1px solid #eceded;}
  th{background:#f5f6f7;} .brand{font-weight:700;} .tera{font-weight:700;}
  .tag{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;}
`;

function doc(title: string, inner: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><style>${BASE_CSS}</style><title>${esc(
    title,
  )}</title></head><body>${inner}<p class="muted" style="margin-top:40px;">Generated by alka<span class="tera">tera</span></p></body></html>`;
}

export interface CoverSheetData {
  organisationName: string;
  certificationType: 'new' | 'recertification' | null;
  submissionDate: string;
  auditorName: string | null;
  contactEmail: string | null;
  requirementStatuses: RequirementStatus[];
}

export function renderCoverSheetHtml(d: CoverSheetData): string {
  const passed = d.requirementStatuses.filter(
    (r) => r.status === 'passed',
  ).length;
  const evaluated = d.requirementStatuses.filter(
    (r) => r.status !== 'future',
  ).length;
  const inner = `
    <h1>B Corp Certification Audit Package</h1>
    <p class="muted">${esc(d.organisationName)}</p>
    <table>
      <tr><th>Organisation</th><td>${esc(d.organisationName)}</td></tr>
      <tr><th>Certification type</th><td>${
        d.certificationType === 'recertification'
          ? 'Recertification (under V2.1)'
          : 'New certification'
      }</td></tr>
      <tr><th>Submission date</th><td>${esc(d.submissionDate)}</td></tr>
      <tr><th>Audit provider</th><td>${esc(d.auditorName ?? 'Not set')}</td></tr>
      <tr><th>Contact</th><td>${esc(d.contactEmail ?? 'Not set')}</td></tr>
      <tr><th>Requirements passed</th><td>${passed} of ${evaluated} evaluated</td></tr>
    </table>`;
  return doc('B Corp Audit Package', inner);
}

export function renderRequirementsSummaryHtml(
  organisationName: string,
  requirementStatuses: RequirementStatus[],
  evidenceCountByReq: Record<string, number>,
): string {
  const rows = requirementStatuses
    .slice()
    .sort((a, b) => a.orderIndex - b.orderIndex)
    .map(
      (r) => `<tr>
        <td>${esc(r.code)}</td>
        <td>${esc(r.name)}</td>
        <td>${esc(r.topicArea)}</td>
        <td>Year ${r.applicableFromYear}</td>
        <td>${esc(r.status)}</td>
        <td>${evidenceCountByReq[r.requirementId] ?? r.evidenceCount}</td>
      </tr>`,
    )
    .join('');
  const inner = `
    <h1>Requirements Summary</h1>
    <p class="muted">${esc(organisationName)}</p>
    <table>
      <tr><th>Code</th><th>Requirement</th><th>Topic</th><th>Year</th><th>Status</th><th>Evidence</th></tr>
      ${rows}
    </table>`;
  return doc('Requirements Summary', inner);
}

export interface RiskToolOutputData {
  organisationName: string;
  completedAt: string | null;
  riskProfile: Record<string, string> | null;
  responses: Record<string, string> | null;
  triggered: string[];
}

export function renderRiskToolHtml(d: RiskToolOutputData): string {
  if (!d.riskProfile) {
    return doc(
      'Risk Tool Output',
      `<h1>Risk Tool Output</h1><p class="muted">${esc(
        d.organisationName,
      )}</p><p>The Risk Tool has not been completed.</p>`,
    );
  }
  const profileRows = Object.entries(d.riskProfile)
    .map(
      ([k, v]) =>
        `<tr><td>${esc(k.replace(/_/g, ' '))}</td><td>${esc(v)}</td></tr>`,
    )
    .join('');
  const inner = `
    <h1>Risk Tool Output</h1>
    <p class="muted">${esc(d.organisationName)} · completed ${esc(
      d.completedAt ?? 'unknown',
    )}</p>
    <h2>Risk profile</h2>
    <table><tr><th>Dimension</th><th>Level</th></tr>${profileRows}</table>
    <h2>Triggered requirements (elevated focus)</h2>
    <p>${d.triggered.length ? esc(d.triggered.join(', ')) : 'None'}</p>`;
  return doc('Risk Tool Output', inner);
}

export interface RecertReportData {
  organisationName: string;
  certificationStartDate: string | null;
  year3Met: number;
  year3Total: number;
  year5Met: number;
  year5Total: number;
  healthTrend: Array<{ date: string; score: number | null }>;
}

export function renderRecertReportHtml(d: RecertReportData): string {
  const trendRows = d.healthTrend
    .map(
      (t) =>
        `<tr><td>${esc(t.date)}</td><td>${
          t.score == null ? '—' : esc(String(t.score))
        }</td></tr>`,
    )
    .join('');
  const inner = `
    <h1>Recertification Readiness Report</h1>
    <p class="muted">${esc(d.organisationName)}</p>
    <table>
      <tr><th>Original certification date</th><td>${esc(
        d.certificationStartDate ?? 'Not set',
      )}</td></tr>
      <tr><th>Year 3 requirements met</th><td>${d.year3Met} of ${d.year3Total}</td></tr>
      <tr><th>Year 5 requirements status</th><td>${d.year5Met} of ${d.year5Total} met</td></tr>
    </table>
    <h2>Health score trend over the cycle</h2>
    <table><tr><th>Date</th><th>Health score</th></tr>${
      trendRows || '<tr><td colspan="2">No history recorded</td></tr>'
    }</table>`;
  return doc('Recertification Readiness Report', inner);
}

export interface BiaManifestRow {
  code: string;
  name: string;
  status: string;
  files: string[];
}

export interface BiaManifestGroup {
  area: string;
  note: string;
  requirements: BiaManifestRow[];
}

/**
 * Manifest that organises requirements and their evidence files by B Corp
 * Impact Topic (B Lab Standards v2.2), so a user uploading to the B Corp
 * assessment knows exactly which file goes against which topic.
 */
export function renderBiaManifestHtml(
  organisationName: string,
  groups: BiaManifestGroup[],
): string {
  const sections = groups
    .map((g) => {
      const rows = g.requirements
        .map(
          (r) => `<tr>
            <td>${esc(r.code)}</td>
            <td>${esc(r.name)}</td>
            <td>${esc(r.status)}</td>
            <td>${
              r.files.length
                ? r.files.map((f) => esc(f)).join('<br>')
                : '<span class="muted">No file uploaded</span>'
            }</td>
          </tr>`,
        )
        .join('');
      return `
        <h2>${esc(g.area)}</h2>
        <p class="muted">${esc(g.note)}</p>
        <table>
          <tr><th>Code</th><th>Requirement</th><th>Status</th><th>Evidence file(s) in this bundle</th></tr>
          ${rows || '<tr><td colspan="4" class="muted">No requirements in this area.</td></tr>'}
        </table>`;
    })
    .join('');
  const inner = `
    <h1>B Corp evidence map</h1>
    <p class="muted">${esc(organisationName)} · B Lab Standards v2.2</p>
    <p>This bundle is organised by the B Corp Foundation Requirements and 7 Impact
    Topics, the same structure as the B Corp assessment. The
    <span class="brand">evidence/</span> folder has one sub-folder per section below;
    each file is listed against the requirement and topic it supports, so you can
    upload it to the matching section of your B Corp assessment.</p>
    ${sections}`;
  return doc('B Corp evidence map', inner);
}

export function buildReadme(
  organisationName: string,
  options: { layout?: 'requirement' | 'bia'; includePending?: boolean } = {},
): string {
  const { layout = 'requirement', includePending = false } = options;
  const evidenceLine =
    layout === 'bia'
      ? `  evidence/                Evidence files in sub-folders by B Corp Impact Topic`
      : `  evidence/                Evidence files, named by requirement`;
  const manifestLine =
    layout === 'bia'
      ? [`  bcorp_evidence_map.pdf   Which evidence file maps to which B Corp Impact Topic`]
      : [];
  const statusLine = includePending
    ? `This bundle includes both verified and unverified (pending) evidence; unverified files are prefixed PENDING- so an auditor can tell them apart.`
    : `This bundle includes verified evidence only.`;
  return [
    `B Corp Certification Audit Package`,
    `Organisation: ${organisationName}`,
    ``,
    `Contents:`,
    `  cover_sheet.pdf          Organisation and submission summary`,
    `  requirements_summary.pdf Full requirement list with pass/fail status`,
    `  risk_tool_output.pdf     Completed Risk Tool responses and profile`,
    ...manifestLine,
    evidenceLine,
    ``,
    statusLine,
    ``,
    `Generated by alkatera. Cross-reference each evidence file with`,
    `requirements_summary.pdf${layout === 'bia' ? ' and bcorp_evidence_map.pdf' : ''}.`,
  ].join('\n');
}
