// Pure HTML renderers for the B Corp audit package PDFs. No server-only /
// Supabase imports so these can be unit-tested.

import type { RequirementStatus } from './scoring';

function esc(s: string | null | undefined): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

const BASE_CSS = `
  body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0a0a0a;margin:40px;}
  h1{font-size:22px;margin:0 0 4px;} h2{font-size:16px;margin:24px 0 8px;}
  .muted{color:#525960;font-size:12px;} table{width:100%;border-collapse:collapse;margin-top:8px;}
  th,td{text-align:left;font-size:12px;padding:6px 8px;border-bottom:1px solid #eceded;}
  th{background:#f5f6f7;} .brand{font-weight:700;} .tera{font-weight:700;}
  .tag{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;}
`;

function doc(title: string, inner: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><style>${BASE_CSS}</style><title>${esc(
    title,
  )}</title></head><body>${inner}<p class="muted" style="margin-top:40px;">Generated by alka<span class="tera">tera</span></p></body></html>`;
}

export interface CoverSheetData {
  organisationName: string;
  certificationType: 'new' | 'recertification' | null;
  submissionDate: string;
  auditorName: string | null;
  contactEmail: string | null;
  requirementStatuses: RequirementStatus[];
}

export function renderCoverSheetHtml(d: CoverSheetData): string {
  const passed = d.requirementStatuses.filter(
    (r) => r.status === 'passed',
  ).length;
  const evaluated = d.requirementStatuses.filter(
    (r) => r.status !== 'future',
  ).length;
  const inner = `
    <h1>B Corp Certification Audit Package</h1>
    <p class="muted">${esc(d.organisationName)}</p>
    <table>
      <tr><th>Organisation</th><td>${esc(d.organisationName)}</td></tr>
      <tr><th>Certification type</th><td>${
        d.certificationType === 'recertification'
          ? 'Recertification (under V2.1)'
          : 'New certification'
      }</td></tr>
      <tr><th>Submission date</th><td>${esc(d.submissionDate)}</td></tr>
      <tr><th>Audit provider</th><td>${esc(d.auditorName ?? 'Not set')}</td></tr>
      <tr><th>Contact</th><td>${esc(d.contactEmail ?? 'Not set')}</td></tr>
      <tr><th>Requirements passed</th><td>${passed} of ${evaluated} evaluated</td></tr>
    </table>`;
  return doc('B Corp Audit Package', inner);
}

export function renderRequirementsSummaryHtml(
  organisationName: string,
  requirementStatuses: RequirementStatus[],
  evidenceCountByReq: Record<string, number>,
): string {
  const rows = requirementStatuses
    .slice()
    .sort((a, b) => a.orderIndex - b.orderIndex)
    .map(
      (r) => `<tr>
        <td>${esc(r.code)}</td>
        <td>${esc(r.name)}</td>
        <td>${esc(r.topicArea)}</td>
        <td>Year ${r.applicableFromYear}</td>
        <td>${esc(r.status)}</td>
        <td>${evidenceCountByReq[r.requirementId] ?? r.evidenceCount}</td>
      </tr>`,
    )
    .join('');
  const inner = `
    <h1>Requirements Summary</h1>
    <p class="muted">${esc(organisationName)}</p>
    <table>
      <tr><th>Code</th><th>Requirement</th><th>Topic</th><th>Year</th><th>Status</th><th>Evidence</th></tr>
      ${rows}
    </table>`;
  return doc('Requirements Summary', inner);
}

export interface RiskToolOutputData {
  organisationName: string;
  completedAt: string | null;
  riskProfile: Record<string, string> | null;
  responses: Record<string, string> | null;
  triggered: string[];
}

export function renderRiskToolHtml(d: RiskToolOutputData): string {
  if (!d.riskProfile) {
    return doc(
      'Risk Tool Output',
      `<h1>Risk Tool Output</h1><p class="muted">${esc(
        d.organisationName,
      )}</p><p>The Risk Tool has not been completed.</p>`,
    );
  }
  const profileRows = Object.entries(d.riskProfile)
    .map(
      ([k, v]) =>
        `<tr><td>${esc(k.replace(/_/g, ' '))}</td><td>${esc(v)}</td></tr>`,
    )
    .join('');
  const inner = `
    <h1>Risk Tool Output</h1>
    <p class="muted">${esc(d.organisationName)} · completed ${esc(
      d.completedAt ?? 'unknown',
    )}</p>
    <h2>Risk profile</h2>
    <table><tr><th>Dimension</th><th>Level</th></tr>${profileRows}</table>
    <h2>Triggered requirements (elevated focus)</h2>
    <p>${d.triggered.length ? esc(d.triggered.join(', ')) : 'None'}</p>`;
  return doc('Risk Tool Output', inner);
}

export interface RecertReportData {
  organisationName: string;
  certificationStartDate: string | null;
  year3Met: number;
  year3Total: number;
  year5Met: number;
  year5Total: number;
  healthTrend: Array<{ date: string; score: number | null }>;
}

export function renderRecertReportHtml(d: RecertReportData): string {
  const trendRows = d.healthTrend
    .map(
      (t) =>
        `<tr><td>${esc(t.date)}</td><td>${
          t.score == null ? '—' : esc(String(t.score))
        }</td></tr>`,
    )
    .join('');
  const inner = `
    <h1>Recertification Readiness Report</h1>
    <p class="muted">${esc(d.organisationName)}</p>
    <table>
      <tr><th>Original certification date</th><td>${esc(
        d.certificationStartDate ?? 'Not set',
      )}</td></tr>
      <tr><th>Year 3 requirements met</th><td>${d.year3Met} of ${d.year3Total}</td></tr>
      <tr><th>Year 5 requirements status</th><td>${d.year5Met} of ${d.year5Total} met</td></tr>
    </table>
    <h2>Health score trend over the cycle</h2>
    <table><tr><th>Date</th><th>Health score</th></tr>${
      trendRows || '<tr><td colspan="2">No history recorded</td></tr>'
    }</table>`;
  return doc('Recertification Readiness Report', inner);
}

export function buildReadme(organisationName: string): string {
  return [
    `B Corp Certification Audit Package`,
    `Organisation: ${organisationName}`,
    ``,
    `Contents:`,
    `  cover_sheet.pdf          Organisation and submission summary`,
    `  requirements_summary.pdf Full requirement list with pass/fail status`,
    `  risk_tool_output.pdf     Completed Risk Tool responses and profile`,
    `  evidence/                Verified evidence files, named by requirement`,
    ``,
    `Generated by alkatera. Each evidence file is named with its requirement`,
    `area and requirement ID for cross-reference with requirements_summary.pdf.`,
  ].join('\n');
}
