export { OnboardingProvider, useOnboarding } from './OnboardingContext'
export type {
  OnboardingFlow,
  OnboardingPhase,
  OnboardingStep,
  OnboardingState,
  OnboardingStepConfig,
  PersonalizationData,
  ScrapedProductDraft,
  UserRole,
  BeverageType,
  CompanySize,
  PrimaryGoal,
  AnnualProductionBucket,
  PersonaChoice,
} from './types'
export {
  MEMBER_ONBOARDING_STEPS,
  ADVISOR_ONBOARDING_STEPS,
  ARRIVAL_STEPS,
  TOTAL_ARRIVAL_STEPS,
  INITIAL_MEMBER_ONBOARDING_STATE,
  INITIAL_ADVISOR_ONBOARDING_STATE,
  INITIAL_ARRIVAL_STATE,
  getStepsForFlow,
  getInitialStateForFlow,
  getStepConfig,
  getNextStep,
  getPreviousStep,
  getProgressPercentage,
} from './types'
