export { OnboardingProvider, useOnboarding } from './OnboardingContext'
export type {
  OnboardingFlow,
  OnboardingPhase,
  OnboardingStep,
  OnboardingState,
  OnboardingStepConfig,
  PersonalizationData,
  UserRole,
  BeverageType,
  CompanySize,
  PrimaryGoal,
} from './types'
export {
  ONBOARDING_STEPS,
  MEMBER_ONBOARDING_STEPS,
  TOTAL_STEPS,
  TOTAL_MEMBER_STEPS,
  PHASE_CONFIG,
  MEMBER_PHASES,
  INITIAL_ONBOARDING_STATE,
  INITIAL_MEMBER_ONBOARDING_STATE,
  getStepsForFlow,
  getInitialStateForFlow,
  getStepConfig,
  getPhaseSteps,
  getNextStep,
  getPreviousStep,
  getProgressPercentage,
  isPhaseComplete,
} from './types'
