export { OnboardingProvider, useOnboarding } from './OnboardingContext'
export type {
  OnboardingFlow,
  OnboardingPhase,
  OnboardingStep,
  OnboardingState,
  OnboardingStepConfig,
  PersonalizationData,
  UserRole,
  BeverageType,
  CompanySize,
  PrimaryGoal,
  AnnualProductionBucket,
  PersonaChoice,
} from './types'
export {
  ONBOARDING_STEPS,
  MEMBER_ONBOARDING_STEPS,
  FAST_TRACK_STEPS,
  ADVISOR_ONBOARDING_STEPS,
  ARRIVAL_STEPS,
  FAST_TRACK_PHASES,
  TOTAL_STEPS,
  TOTAL_MEMBER_STEPS,
  TOTAL_FAST_TRACK_STEPS,
  TOTAL_ADVISOR_STEPS,
  TOTAL_ARRIVAL_STEPS,
  PHASE_CONFIG,
  MEMBER_PHASES,
  ADVISOR_PHASES,
  INITIAL_ONBOARDING_STATE,
  INITIAL_MEMBER_ONBOARDING_STATE,
  INITIAL_FAST_TRACK_STATE,
  INITIAL_ADVISOR_ONBOARDING_STATE,
  INITIAL_ARRIVAL_STATE,
  getStepsForFlow,
  getInitialStateForFlow,
  getStepConfig,
  getPhaseSteps,
  getNextStep,
  getPreviousStep,
  getProgressPercentage,
  isPhaseComplete,
} from './types'
