'use client';

import { Navigation } from '@/marketing/components/Navigation';
import { Footer } from '@/marketing/components/Footer';
import { useState } from 'react';
import { ContactModal } from '@/marketing/components/ContactModal';

export function TermsPageClient() {
  const [isContactOpen, setIsContactOpen] = useState(false);

  return (
    <div className="bg-[#050505] min-h-screen w-full text-white selection:bg-[#ccff00] selection:text-black overflow-x-hidden">
      <Navigation onOpenContact={() => setIsContactOpen(true)} />

      <main className="max-w-3xl mx-auto px-6 pt-40 pb-24">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms and Conditions</h1>
        <p className="text-gray-500 font-mono text-sm mb-12">Last Updated: 17 January 2026</p>

        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 leading-relaxed">
          <p>
            These Terms and Conditions (&ldquo;Terms&rdquo;) govern your access to and use of the Alkatera platform and services provided by Avallen Solutions Ltd trading as Alkatera (&ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;). By accessing or using our platform, you agree to be bound by these Terms.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">1. Definitions</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong className="text-white">&ldquo;Platform&rdquo;</strong> means the Alkatera web application, APIs, and related services</li>
              <li><strong className="text-white">&ldquo;User&rdquo;, &ldquo;you&rdquo;, &ldquo;your&rdquo;</strong> means the individual or organisation accessing the Platform</li>
              <li><strong className="text-white">&ldquo;Subscription&rdquo;</strong> means the paid service plan selected by the User</li>
              <li><strong className="text-white">&ldquo;Content&rdquo;</strong> means all data, information, and materials uploaded to or generated by the Platform</li>
              <li><strong className="text-white">&ldquo;Environmental Data&rdquo;</strong> means sustainability metrics, emissions data, and related information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">2. Account Registration</h2>
            <p>2.1 To use the Platform, you must create an account and provide accurate, complete information. You are responsible for maintaining the confidentiality of your account credentials.</p>
            <p>2.2 You must be at least 18 years old and have the legal authority to bind yourself and your organisation to these Terms.</p>
            <p>2.3 You are responsible for all activities that occur under your account and must notify us immediately of any unauthorised access.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">3. Subscription Plans and Payment</h2>
            <p>3.1 We offer various subscription tiers (Seed, Blossom, Canopy) with different features and usage limits. Plan details are available on our website.</p>
            <p>3.2 Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law.</p>
            <p>3.3 We reserve the right to modify pricing with 30 days&apos; notice. Continued use after price changes constitutes acceptance.</p>
            <p>3.4 If payment fails, we may suspend access until payment is received.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">4. Permitted Use</h2>
            <p>4.1 Subject to these Terms, we grant you a limited, non-exclusive, non-transferable licence to access and use the Platform for your internal business purposes.</p>
            <p>4.2 You may use the Platform to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Track and analyse environmental impact metrics</li>
              <li>Generate sustainability reports for your organisation</li>
              <li>Manage supply chain sustainability data</li>
              <li>Prepare for B Corp and other sustainability certifications</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">5. Prohibited Conduct</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Platform for any unlawful purpose</li>
              <li>Upload false, misleading, or fraudulent environmental data</li>
              <li>Attempt to gain unauthorised access to the Platform or other users&apos; accounts</li>
              <li>Reverse engineer, decompile, or disassemble the Platform</li>
              <li>Use automated systems to access the Platform without permission</li>
              <li>Resell, sublicence, or redistribute access to the Platform</li>
              <li>Interfere with or disrupt the Platform&apos;s infrastructure</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">6. Your Content and Data</h2>
            <p>6.1 You retain ownership of all Content you upload to the Platform. By uploading Content, you grant us a licence to use, process, and store it to provide our services.</p>
            <p>6.2 You are responsible for the accuracy and legality of your Content. You represent that you have the right to share any data uploaded.</p>
            <p>6.3 We may use anonymised and aggregated data for industry benchmarking and research purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">7. Intellectual Property</h2>
            <p>7.1 The Platform, including its software, design, algorithms, and methodologies, is owned by us and protected by intellectual property laws.</p>
            <p>7.2 Reports and analytics generated by the Platform may be used by you for your business purposes, subject to attribution requirements where applicable.</p>
            <p>7.3 You may not use our trademarks, logos, or branding without written permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">8. Environmental Data Accuracy</h2>
            <p>8.1 Our Platform calculates environmental metrics based on established methodologies and the data you provide.</p>
            <p>8.2 The accuracy of outputs depends on the quality and completeness of input data. We do not guarantee that calculations meet specific regulatory or certification requirements.</p>
            <p>8.3 You should verify outputs independently before making claims or submitting for certification.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">9. Third-Party Integrations</h2>
            <p>The Platform may integrate with third-party services. Your use of such integrations is subject to those providers&apos; terms. We are not responsible for third-party services.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">10. Service Availability</h2>
            <p>10.1 We strive to maintain Platform availability but do not guarantee uninterrupted access. We may perform maintenance with reasonable notice.</p>
            <p>10.2 We may modify, suspend, or discontinue features with notice. Material changes to core functionality will be communicated 30 days in advance.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">11. Limitation of Liability</h2>
            <p>11.1 To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages.</p>
            <p>11.2 Our total liability for any claims arising from these Terms or use of the Platform shall not exceed the fees paid by you in the 12 months preceding the claim.</p>
            <p>11.3 We are not liable for decisions made based on Platform outputs or for regulatory penalties related to your environmental reporting.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">12. Indemnification</h2>
            <p>You agree to indemnify and hold us harmless from claims arising from your use of the Platform, your Content, violation of these Terms, or violation of any third-party rights.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">13. Termination</h2>
            <p>13.1 You may terminate your account at any time. Refunds for prepaid subscriptions are not provided except as required by law.</p>
            <p>13.2 We may terminate or suspend your account for violation of these Terms, non-payment, or at our discretion with 30 days&apos; notice.</p>
            <p>13.3 Upon termination, you may export your data within 30 days. After this period, we may delete your data.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">14. Governing Law and Disputes</h2>
            <p>14.1 These Terms are governed by the laws of England and Wales.</p>
            <p>14.2 Any disputes shall be resolved through negotiation. If unresolved, disputes shall be submitted to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">15. Changes to Terms</h2>
            <p>We may modify these Terms at any time. Material changes will be notified via email or Platform notification at least 30 days before taking effect. Continued use constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">16. General Provisions</h2>
            <p>16.1 These Terms constitute the entire agreement between you and us regarding the Platform.</p>
            <p>16.2 Our failure to enforce any provision does not waive our right to do so later.</p>
            <p>16.3 If any provision is found unenforceable, the remaining provisions remain in effect.</p>
            <p>16.4 You may not assign these Terms without our consent.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">17. Contact Information</h2>
            <p>For questions about these Terms, contact us:</p>
            <p className="mt-2">
              Avallen Solutions Ltd trading as Alkatera<br />
              Email: <a href="mailto:hello@alkatera.com" className="text-[#ccff00] hover:underline">hello@alkatera.com</a><br />
              Website: <a href="https://alkatera.com" className="text-[#ccff00] hover:underline">https://alkatera.com</a>
            </p>
          </section>
        </div>
      </main>

      <Footer />
      <ContactModal isOpen={isContactOpen} onClose={() => setIsContactOpen(false)} />
    </div>
  );
}
