import jsPDF from 'jspdf';
import {
  drawDonutChart,
  drawPieChart,
  drawHorizontalBarChart,
  drawProgressBar,
  drawChartLegend,
  drawGaugeChart,
  drawScopeBreakdownBars,
  PASSPORT_COLORS,
  type ChartDataItem,
  type BarChartItem,
} from './pdf-chart-renderer';

export interface GHGBreakdownItem {
  gas: string;
  value: number;
  unit: string;
}

export interface LifecycleStageItem {
  stage: string;
  value: number;
  percentage: number;
  color: string;
  description?: string;
}

export interface WaterSourceItem {
  source: string;
  location?: string;
  volume: number;
  unit: string;
  riskLevel?: 'LOW' | 'MEDIUM' | 'HIGH';
  awareFactor?: number;
  scarcityImpact?: number;
}

export interface WasteStreamItem {
  stream: string;
  disposition: string;
  mass: number;
  unit: string;
  circularityScore?: number;
  recyclable: boolean;
  color: string;
}

export interface LandUseItem {
  material: string;
  origin?: string;
  mass: number;
  landIntensity: number;
  totalFootprint: number;
  unit: string;
}

export interface DataSourceItem {
  name: string;
  description?: string;
  count?: number;
}

export interface PassportPDFData {
  meta: {
    title: string;
    productName: string;
    version: string;
    date: string;
    author: string;
    referenceNumber?: string;
    heroImageBase64?: string;
    organizationName: string;
    organizationLogoBase64?: string;
    functionalUnit: string;
    functionalUnitDescription?: string;
  };
  executiveSummary: {
    heading: string;
    content: string;
    keyHighlight?: string;
    assessmentPeriod?: string;
    publishedDate?: string;
  };
  methodology: {
    systemBoundary: string;
    includedStages: string[];
    excludedStages: string[];
    dataSources: DataSourceItem[];
    standards: string[];
    cutOffCriteria?: string;
  };
  climateImpact: {
    totalCarbon: number;
    unit: string;
    lifecycleBreakdown: LifecycleStageItem[];
    scope1?: number;
    scope2?: number;
    scope3?: number;
    ghgBreakdown?: GHGBreakdownItem[];
    benchmarkName?: string;
    benchmarkValue?: number;
    reductionPercentage?: number;
  };
  waterFootprint?: {
    total: number;
    unit: string;
    scarcityWeighted?: number;
    breakdown: ChartDataItem[];
    sources?: WaterSourceItem[];
  };
  wasteFootprint?: {
    total: number;
    unit: string;
    recyclingRate?: number;
    circularityScore?: number;
    breakdown: WasteStreamItem[];
  };
  landUse?: {
    total: number;
    unit: string;
    breakdown?: LandUseItem[];
  };
  dataQuality?: {
    overallScore: number;
    primaryDataPercentage?: number;
    temporalCoverage?: string;
    geographicCoverage?: string;
  };
  conclusion: {
    title: string;
    content: string;
  };
  passportUrl?: string;
}

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

let currentPageNumber = 1;

function addPageFooter(doc: jsPDF, generationDate: string): void {
  const footerY = PAGE_HEIGHT - 12;

  doc.setFillColor(PASSPORT_COLORS.stone900);
  doc.rect(0, PAGE_HEIGHT - 18, PAGE_WIDTH, 18, 'F');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(PASSPORT_COLORS.stone500);
  doc.text('Generated by', MARGIN, footerY);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(PASSPORT_COLORS.stone300);
  doc.text('Alkatera', MARGIN + 26, footerY);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(PASSPORT_COLORS.stone500);
  doc.text('Platform', MARGIN + 41, footerY);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor('#FFFFFF');
  doc.text(String(currentPageNumber), PAGE_WIDTH / 2, footerY, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(PASSPORT_COLORS.stone500);
  doc.text(`ISO 14040/44 Compliant  |  ${generationDate}`, PAGE_WIDTH - MARGIN, footerY, { align: 'right' });
}

function addNewPage(doc: jsPDF, generationDate: string): void {
  addPageFooter(doc, generationDate);
  doc.addPage();
  currentPageNumber++;
}

function drawSectionHeader(
  doc: jsPDF,
  number: string,
  title: string,
  y: number,
  isDark: boolean = false
): number {
  const textColor = isDark ? '#FFFFFF' : PASSPORT_COLORS.stone900;
  const accentColor = isDark ? PASSPORT_COLORS.brandAccent : PASSPORT_COLORS.lime700;
  const borderColor = isDark ? PASSPORT_COLORS.stone700 : PASSPORT_COLORS.stone200;

  doc.setFont('courier', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(accentColor);
  doc.text(number, MARGIN, y);

  doc.setFont('times', 'normal');
  doc.setFontSize(28);
  doc.setTextColor(textColor);
  doc.text(title, MARGIN + 18, y);

  doc.setDrawColor(borderColor);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y + 6, PAGE_WIDTH - MARGIN, y + 6);

  return y + 18;
}

function drawSubSectionHeader(
  doc: jsPDF,
  title: string,
  y: number,
  isDark: boolean = false
): number {
  const textColor = isDark ? '#FFFFFF' : PASSPORT_COLORS.stone900;

  doc.setFont('times', 'normal');
  doc.setFontSize(16);
  doc.setTextColor(textColor);
  doc.text(title, MARGIN, y);

  return y + 10;
}

function drawCard(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  isDark: boolean = false
): void {
  const bgColor = isDark ? 'rgba(255,255,255,0.05)' : PASSPORT_COLORS.stone50;
  const borderColor = isDark ? PASSPORT_COLORS.stone700 : PASSPORT_COLORS.stone200;

  if (isDark) {
    doc.setFillColor(40, 40, 40);
  } else {
    doc.setFillColor(bgColor);
  }
  doc.roundedRect(x, y, width, height, 4, 4, 'F');

  doc.setDrawColor(borderColor);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, width, height, 4, 4, 'S');
}

function drawMetricCard(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  label: string,
  value: string,
  unit: string,
  color: string,
  isDark: boolean = true
): number {
  const cardHeight = 45;
  drawCard(doc, x, y, width, cardHeight, isDark);

  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(isDark ? PASSPORT_COLORS.stone400 : PASSPORT_COLORS.stone500);
  doc.text(label.toUpperCase(), x + 8, y + 14);

  doc.setFont('times', 'normal');
  doc.setFontSize(24);
  doc.setTextColor(color);
  doc.text(value, x + 8, y + 34);

  doc.setFont('times', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(isDark ? PASSPORT_COLORS.stone400 : PASSPORT_COLORS.stone500);
  const valueWidth = doc.getTextWidth(value);
  doc.text(unit, x + 10 + valueWidth, y + 34);

  return y + cardHeight + 8;
}

function drawBreakdownCard(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  item: LifecycleStageItem,
  unit: string,
  isDark: boolean = true
): number {
  const cardHeight = 50;
  drawCard(doc, x, y, width, cardHeight, isDark);

  doc.setFillColor(item.color);
  doc.circle(x + 12, y + 14, 4, 'F');

  doc.setFont('courier', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(isDark ? PASSPORT_COLORS.stone400 : PASSPORT_COLORS.stone500);
  doc.text(item.stage.toUpperCase(), x + 20, y + 16);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(isDark ? '#FFFFFF' : PASSPORT_COLORS.stone900);
  doc.text(`${item.value.toFixed(3)} ${unit}`, x + 8, y + 32);

  doc.setFont('courier', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(PASSPORT_COLORS.brandAccent);
  doc.text(`${item.percentage.toFixed(1)}%`, x + 8, y + 44);

  return cardHeight;
}

function drawCoverPage(doc: jsPDF, data: PassportPDFData): void {
  doc.setFillColor(PASSPORT_COLORS.stone900);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  if (data.meta.heroImageBase64) {
    try {
      doc.addImage(data.meta.heroImageBase64, 'JPEG', 0, 0, PAGE_WIDTH, 140);

      doc.setFillColor(28, 25, 23);
      doc.rect(0, 100, PAGE_WIDTH, 40, 'F');
    } catch {
      doc.setFillColor(PASSPORT_COLORS.stone800);
      doc.rect(0, 0, PAGE_WIDTH, 140, 'F');
    }
  } else {
    doc.setFillColor(PASSPORT_COLORS.stone800);
    doc.rect(0, 0, PAGE_WIDTH, 140, 'F');

    doc.setFillColor(50, 50, 45);
    doc.circle(PAGE_WIDTH - 40, 60, 100, 'F');
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor('#FFFFFF');
  doc.text('ALKATERA INTELLIGENCE', MARGIN, 25);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text('Product Passport', MARGIN, 33);

  if (data.meta.referenceNumber) {
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(PASSPORT_COLORS.stone400);
    doc.text(`REF: ${data.meta.referenceNumber}`, PAGE_WIDTH - MARGIN, 25, { align: 'right' });
  }

  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text(data.meta.date, PAGE_WIDTH - MARGIN, 33, { align: 'right' });

  doc.setFillColor(PASSPORT_COLORS.brandAccent);
  doc.roundedRect(MARGIN, 100, 120, 20, 2, 2, 'F');

  doc.setFont('courier', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(PASSPORT_COLORS.stone900);
  doc.text('PRODUCT FOOTPRINT ANALYSIS', MARGIN + 8, 113);

  doc.setFont('times', 'normal');
  doc.setFontSize(42);
  doc.setTextColor('#FFFFFF');

  const productName = data.meta.productName;
  const maxWidth = CONTENT_WIDTH;
  if (doc.getTextWidth(productName) > maxWidth) {
    doc.setFontSize(32);
  }
  doc.text(productName, MARGIN, 170);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text(data.meta.organizationName, MARGIN, 185);

  doc.setDrawColor(PASSPORT_COLORS.stone700);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, 200, PAGE_WIDTH - MARGIN, 200);

  doc.setFillColor(50, 50, 50);
  doc.roundedRect(MARGIN, 215, CONTENT_WIDTH, 50, 4, 4, 'F');

  doc.setDrawColor(PASSPORT_COLORS.stone600);
  doc.setLineWidth(0.3);
  doc.roundedRect(MARGIN, 215, CONTENT_WIDTH, 50, 4, 4, 'S');

  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text('FUNCTIONAL UNIT', MARGIN + 12, 230);

  doc.setFont('times', 'normal');
  doc.setFontSize(18);
  doc.setTextColor('#FFFFFF');
  doc.text(data.meta.functionalUnit, MARGIN + 12, 250);

  if (data.meta.functionalUnitDescription) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(PASSPORT_COLORS.stone400);
    const descLines = doc.splitTextToSize(data.meta.functionalUnitDescription, CONTENT_WIDTH - 24);
    doc.text(descLines.slice(0, 1), MARGIN + 12, 260);
  }

  addPageFooter(doc, data.meta.date);
}

function drawExecutiveSummaryPage(doc: jsPDF, data: PassportPDFData): void {
  doc.setFillColor(PASSPORT_COLORS.stone50);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  let y = 30;
  y = drawSectionHeader(doc, '01', 'Executive Summary', y, false);

  y += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(PASSPORT_COLORS.stone600);
  const contentLines = doc.splitTextToSize(data.executiveSummary.content, CONTENT_WIDTH * 0.6);
  doc.text(contentLines, MARGIN, y);

  const contentHeight = contentLines.length * 5;

  if (data.executiveSummary.keyHighlight) {
    const highlightX = MARGIN + CONTENT_WIDTH * 0.65;
    const highlightWidth = CONTENT_WIDTH * 0.35;

    doc.setFillColor(PASSPORT_COLORS.lime700);
    doc.roundedRect(highlightX, y - 5, highlightWidth, 60, 4, 4, 'F');

    doc.setFont('courier', 'bold');
    doc.setFontSize(8);
    doc.setTextColor('#FFFFFF');
    doc.text('KEY HIGHLIGHT', highlightX + 10, y + 10);

    doc.setFont('times', 'normal');
    doc.setFontSize(11);
    doc.setTextColor('#FFFFFF');
    const highlightLines = doc.splitTextToSize(data.executiveSummary.keyHighlight, highlightWidth - 20);
    doc.text(highlightLines.slice(0, 4), highlightX + 10, y + 25);
  }

  y += Math.max(contentHeight, 70) + 20;

  const infoCardsY = y;
  const cardWidth = (CONTENT_WIDTH - 20) / 3;

  if (data.executiveSummary.assessmentPeriod) {
    drawCard(doc, MARGIN, infoCardsY, cardWidth, 40, false);
    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(PASSPORT_COLORS.stone500);
    doc.text('ASSESSMENT PERIOD', MARGIN + 8, infoCardsY + 15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(PASSPORT_COLORS.stone900);
    doc.text(data.executiveSummary.assessmentPeriod, MARGIN + 8, infoCardsY + 30);
  }

  if (data.executiveSummary.publishedDate) {
    drawCard(doc, MARGIN + cardWidth + 10, infoCardsY, cardWidth, 40, false);
    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(PASSPORT_COLORS.stone500);
    doc.text('PUBLISHED', MARGIN + cardWidth + 18, infoCardsY + 15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(PASSPORT_COLORS.stone900);
    doc.text(data.executiveSummary.publishedDate, MARGIN + cardWidth + 18, infoCardsY + 30);
  }

  drawCard(doc, MARGIN + (cardWidth + 10) * 2, infoCardsY, cardWidth, 40, false);
  doc.setFont('courier', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(PASSPORT_COLORS.stone500);
  doc.text('VERSION', MARGIN + (cardWidth + 10) * 2 + 8, infoCardsY + 15);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(PASSPORT_COLORS.stone900);
  doc.text(data.meta.version, MARGIN + (cardWidth + 10) * 2 + 8, infoCardsY + 30);

  y = infoCardsY + 55;

  if (data.dataQuality) {
    y = drawSubSectionHeader(doc, 'Data Quality Assessment', y, false);
    y += 5;

    const gaugeX = MARGIN + 40;
    drawGaugeChart(
      doc,
      data.dataQuality.overallScore,
      100,
      gaugeX,
      y + 30,
      25,
      'DQI SCORE',
      PASSPORT_COLORS.lime600
    );

    const qualityInfoX = MARGIN + 100;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(PASSPORT_COLORS.stone600);

    if (data.dataQuality.primaryDataPercentage !== undefined) {
      doc.text(`Primary Data: ${data.dataQuality.primaryDataPercentage}%`, qualityInfoX, y + 15);
    }
    if (data.dataQuality.temporalCoverage) {
      doc.text(`Temporal Coverage: ${data.dataQuality.temporalCoverage}`, qualityInfoX, y + 27);
    }
    if (data.dataQuality.geographicCoverage) {
      doc.text(`Geographic Coverage: ${data.dataQuality.geographicCoverage}`, qualityInfoX, y + 39);
    }
  }

  addPageFooter(doc, data.meta.date);
}

function drawMethodologyPage(doc: jsPDF, data: PassportPDFData): void {
  doc.setFillColor('#FFFFFF');
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  let y = 30;
  y = drawSectionHeader(doc, '02', 'Methodology', y, false);

  y += 10;
  doc.setFont('times', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(PASSPORT_COLORS.stone900);
  doc.text('System Boundary', MARGIN, y);

  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(PASSPORT_COLORS.stone600);
  doc.text(data.methodology.systemBoundary, MARGIN, y);

  y += 15;

  const halfWidth = (CONTENT_WIDTH - 10) / 2;

  drawCard(doc, MARGIN, y, halfWidth, 70, false);
  doc.setFont('courier', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.lime700);
  doc.text('INCLUDED STAGES', MARGIN + 8, y + 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(PASSPORT_COLORS.stone700);
  let stageY = y + 28;
  data.methodology.includedStages.slice(0, 5).forEach((stage) => {
    doc.setTextColor(PASSPORT_COLORS.green500);
    doc.text('>', MARGIN + 8, stageY);
    doc.setTextColor(PASSPORT_COLORS.stone700);
    doc.text(stage, MARGIN + 16, stageY);
    stageY += 10;
  });

  drawCard(doc, MARGIN + halfWidth + 10, y, halfWidth, 70, false);
  doc.setFont('courier', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.red500);
  doc.text('EXCLUDED STAGES', MARGIN + halfWidth + 18, y + 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  stageY = y + 28;
  data.methodology.excludedStages.slice(0, 5).forEach((stage) => {
    doc.setTextColor(PASSPORT_COLORS.red400);
    doc.text('x', MARGIN + halfWidth + 18, stageY);
    doc.setTextColor(PASSPORT_COLORS.stone500);
    doc.text(stage, MARGIN + halfWidth + 26, stageY);
    stageY += 10;
  });

  y += 85;

  y = drawSubSectionHeader(doc, 'Data Sources', y, false);
  y += 5;

  const sourceCardWidth = (CONTENT_WIDTH - 15) / 3;
  let sourceX = MARGIN;
  let sourceY = y;

  data.methodology.dataSources.slice(0, 6).forEach((source, index) => {
    if (index > 0 && index % 3 === 0) {
      sourceX = MARGIN;
      sourceY += 45;
    }

    drawCard(doc, sourceX, sourceY, sourceCardWidth, 40, false);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(PASSPORT_COLORS.stone900);
    doc.text(source.name, sourceX + 8, sourceY + 15);

    if (source.description) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(PASSPORT_COLORS.stone500);
      const descLines = doc.splitTextToSize(source.description, sourceCardWidth - 16);
      doc.text(descLines.slice(0, 2), sourceX + 8, sourceY + 26);
    }

    if (source.count !== undefined) {
      doc.setFillColor(PASSPORT_COLORS.lime600);
      doc.roundedRect(sourceX + sourceCardWidth - 25, sourceY + 5, 20, 12, 2, 2, 'F');
      doc.setFont('courier', 'bold');
      doc.setFontSize(8);
      doc.setTextColor('#FFFFFF');
      doc.text(String(source.count), sourceX + sourceCardWidth - 15, sourceY + 13, { align: 'center' });
    }

    sourceX += sourceCardWidth + 7.5;
  });

  y = sourceY + 55;

  if (data.methodology.standards.length > 0) {
    y = drawSubSectionHeader(doc, 'Compliance Standards', y, false);
    y += 5;

    let badgeX = MARGIN;
    data.methodology.standards.forEach((standard) => {
      const badgeWidth = doc.getTextWidth(standard) + 16;

      if (badgeX + badgeWidth > PAGE_WIDTH - MARGIN) {
        badgeX = MARGIN;
        y += 18;
      }

      doc.setFillColor(PASSPORT_COLORS.stone100);
      doc.roundedRect(badgeX, y, badgeWidth, 14, 3, 3, 'F');

      doc.setFont('courier', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(PASSPORT_COLORS.stone700);
      doc.text(standard, badgeX + 8, y + 10);

      badgeX += badgeWidth + 8;
    });
  }

  addPageFooter(doc, data.meta.date);
}

function drawClimateImpactPage(doc: jsPDF, data: PassportPDFData): void {
  doc.setFillColor(PASSPORT_COLORS.stone900);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  doc.setFillColor(40, 42, 35);
  doc.circle(PAGE_WIDTH - 30, 50, 120, 'F');

  let y = 30;
  y = drawSectionHeader(doc, '03', 'Climate Impact', y, true);

  y += 5;
  drawSubSectionHeader(doc, 'Carbon Footprint', y, true);

  const totalValueY = y + 15;
  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text('TOTAL CARBON FOOTPRINT', MARGIN, totalValueY);

  doc.setFont('times', 'normal');
  doc.setFontSize(48);
  doc.setTextColor(PASSPORT_COLORS.brandAccent);
  doc.text(data.climateImpact.totalCarbon.toFixed(2), MARGIN, totalValueY + 35);

  doc.setFont('times', 'normal');
  doc.setFontSize(18);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  const carbonValueWidth = doc.getTextWidth(data.climateImpact.totalCarbon.toFixed(2));
  doc.text(data.climateImpact.unit, MARGIN + carbonValueWidth * 1.8 + 5, totalValueY + 35);

  if (data.climateImpact.lifecycleBreakdown.length > 0) {
    const chartX = PAGE_WIDTH - MARGIN - 70;
    const chartY = totalValueY + 15;
    const chartData: ChartDataItem[] = data.climateImpact.lifecycleBreakdown.map(item => ({
      name: item.stage,
      value: item.percentage,
      color: item.color,
    }));

    drawDonutChart(doc, chartData, chartX, chartY, 35, 20);
  }

  y = totalValueY + 60;

  if (data.climateImpact.benchmarkName && data.climateImpact.reductionPercentage !== undefined) {
    drawCard(doc, MARGIN, y, CONTENT_WIDTH * 0.55, 40, true);

    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(PASSPORT_COLORS.lime400);
    doc.text(`VS. ${data.climateImpact.benchmarkName.toUpperCase()}`, MARGIN + 10, y + 14);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(PASSPORT_COLORS.brandAccent);
    doc.text(`-${data.climateImpact.reductionPercentage}%`, MARGIN + 10, y + 32);

    drawProgressBar(
      doc,
      data.climateImpact.reductionPercentage,
      100,
      MARGIN + 60,
      y + 24,
      CONTENT_WIDTH * 0.55 - 80,
      6,
      PASSPORT_COLORS.brandAccent,
      PASSPORT_COLORS.stone700
    );

    y += 50;
  }

  y += 10;
  drawSubSectionHeader(doc, 'Lifecycle Breakdown', y, true);
  y += 10;

  const cardWidth = (CONTENT_WIDTH - 24) / 4;
  let cardX = MARGIN;

  data.climateImpact.lifecycleBreakdown.slice(0, 4).forEach((item, index) => {
    drawBreakdownCard(doc, cardX, y, cardWidth, item, data.climateImpact.unit, true);
    cardX += cardWidth + 8;
  });

  y += 65;

  if (data.climateImpact.scope1 !== undefined && data.climateImpact.scope2 !== undefined && data.climateImpact.scope3 !== undefined) {
    drawSubSectionHeader(doc, 'GHG Protocol Scope Breakdown', y, true);
    y += 10;

    y = drawScopeBreakdownBars(
      doc,
      data.climateImpact.scope1,
      data.climateImpact.scope2,
      data.climateImpact.scope3,
      MARGIN,
      y,
      CONTENT_WIDTH
    );

    y += 10;
  }

  if (data.climateImpact.ghgBreakdown && data.climateImpact.ghgBreakdown.length > 0) {
    drawSubSectionHeader(doc, 'GHG Gas Breakdown (IPCC AR6)', y, true);
    y += 10;

    const ghgBarData: BarChartItem[] = data.climateImpact.ghgBreakdown.map((item, index) => {
      const colors = ['#60A5FA', '#4ADE80', '#FBBF24', '#F87171'];
      return {
        name: item.gas,
        value: item.value,
        color: colors[index % colors.length],
        maxValue: Math.max(...data.climateImpact.ghgBreakdown!.map(g => g.value)),
      };
    });

    let ghgY = y;
    ghgBarData.forEach((item) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(PASSPORT_COLORS.stone400);
      doc.text(item.name, MARGIN, ghgY + 6);

      drawProgressBar(
        doc,
        item.value,
        item.maxValue!,
        MARGIN + 50,
        ghgY,
        CONTENT_WIDTH - 100,
        8,
        item.color,
        PASSPORT_COLORS.stone700
      );

      doc.setFont('courier', 'bold');
      doc.setFontSize(8);
      doc.setTextColor('#FFFFFF');
      doc.text(`${item.value.toFixed(4)}`, PAGE_WIDTH - MARGIN, ghgY + 6, { align: 'right' });

      ghgY += 14;
    });
  }

  addPageFooter(doc, data.meta.date);
}

function drawWaterFootprintPage(doc: jsPDF, data: PassportPDFData): void {
  if (!data.waterFootprint) return;

  doc.setFillColor(PASSPORT_COLORS.stone900);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  let y = 30;
  y = drawSectionHeader(doc, '04', 'Water Footprint', y, true);

  y += 5;
  const halfWidth = (CONTENT_WIDTH - 10) / 2;

  drawMetricCard(
    doc,
    MARGIN,
    y,
    halfWidth,
    'Total Water Consumption',
    data.waterFootprint.total.toFixed(1),
    data.waterFootprint.unit,
    PASSPORT_COLORS.blue400,
    true
  );

  if (data.waterFootprint.scarcityWeighted !== undefined) {
    drawMetricCard(
      doc,
      MARGIN + halfWidth + 10,
      y,
      halfWidth,
      'Scarcity Weighted (AWARE)',
      data.waterFootprint.scarcityWeighted.toFixed(2),
      'L eq.',
      '#3B82F6',
      true
    );
  }

  y += 60;

  if (data.waterFootprint.breakdown.length > 0) {
    drawSubSectionHeader(doc, 'Water Sources Breakdown', y, true);
    y += 10;

    const chartX = MARGIN + 50;
    const chartY = y + 35;

    drawPieChart(doc, data.waterFootprint.breakdown, chartX, chartY, 30);

    const legendX = MARGIN + 110;
    drawChartLegend(doc, data.waterFootprint.breakdown, legendX, y + 10, 1, 60, 14);
  }

  y += 90;

  if (data.waterFootprint.sources && data.waterFootprint.sources.length > 0) {
    drawSubSectionHeader(doc, 'Water Sources by Location', y, true);
    y += 10;

    doc.setFont('courier', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(PASSPORT_COLORS.stone400);
    doc.text('SOURCE', MARGIN, y);
    doc.text('LOCATION', MARGIN + 45, y);
    doc.text('VOLUME', MARGIN + 95, y);
    doc.text('RISK', MARGIN + 125, y);
    doc.text('AWARE', MARGIN + 150, y);

    doc.setDrawColor(PASSPORT_COLORS.stone700);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y + 4, PAGE_WIDTH - MARGIN, y + 4);

    y += 12;

    data.waterFootprint.sources.slice(0, 6).forEach((source) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor('#FFFFFF');
      doc.text(source.source.substring(0, 15), MARGIN, y);

      doc.setTextColor(PASSPORT_COLORS.stone400);
      doc.text(source.location?.substring(0, 15) || '-', MARGIN + 45, y);

      doc.setTextColor('#FFFFFF');
      doc.text(`${source.volume.toFixed(1)} ${source.unit}`, MARGIN + 95, y);

      if (source.riskLevel) {
        const riskColors: Record<string, string> = {
          LOW: PASSPORT_COLORS.green400,
          MEDIUM: PASSPORT_COLORS.amber400,
          HIGH: PASSPORT_COLORS.red400,
        };
        doc.setTextColor(riskColors[source.riskLevel] || PASSPORT_COLORS.stone400);
        doc.text(source.riskLevel, MARGIN + 125, y);
      }

      if (source.awareFactor !== undefined) {
        doc.setTextColor(PASSPORT_COLORS.stone400);
        doc.text(source.awareFactor.toFixed(2), MARGIN + 150, y);
      }

      y += 10;
    });
  }

  addPageFooter(doc, data.meta.date);
}

function drawWasteFootprintPage(doc: jsPDF, data: PassportPDFData): void {
  if (!data.wasteFootprint) return;

  doc.setFillColor(PASSPORT_COLORS.stone900);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  let y = 30;
  y = drawSectionHeader(doc, '05', 'Circularity & Waste', y, true);

  y += 5;
  const thirdWidth = (CONTENT_WIDTH - 20) / 3;

  drawMetricCard(
    doc,
    MARGIN,
    y,
    thirdWidth,
    'Total Waste',
    data.wasteFootprint.total.toFixed(3),
    data.wasteFootprint.unit,
    PASSPORT_COLORS.orange400,
    true
  );

  if (data.wasteFootprint.recyclingRate !== undefined) {
    drawCard(doc, MARGIN + thirdWidth + 10, y, thirdWidth, 45, true);

    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(PASSPORT_COLORS.stone400);
    doc.text('RECYCLING RATE', MARGIN + thirdWidth + 18, y + 14);

    doc.setFont('times', 'normal');
    doc.setFontSize(20);
    doc.setTextColor(PASSPORT_COLORS.green400);
    doc.text(`${data.wasteFootprint.recyclingRate}%`, MARGIN + thirdWidth + 18, y + 32);

    drawProgressBar(
      doc,
      data.wasteFootprint.recyclingRate,
      100,
      MARGIN + thirdWidth + 50,
      y + 26,
      thirdWidth - 45,
      6,
      PASSPORT_COLORS.green500,
      PASSPORT_COLORS.stone700
    );
  }

  if (data.wasteFootprint.circularityScore !== undefined) {
    drawCard(doc, MARGIN + (thirdWidth + 10) * 2, y, thirdWidth, 45, true);

    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(PASSPORT_COLORS.stone400);
    doc.text('CIRCULARITY SCORE', MARGIN + (thirdWidth + 10) * 2 + 8, y + 14);

    doc.setFont('times', 'normal');
    doc.setFontSize(20);
    doc.setTextColor(PASSPORT_COLORS.emerald400);
    doc.text(`${data.wasteFootprint.circularityScore.toFixed(1)} / 10`, MARGIN + (thirdWidth + 10) * 2 + 8, y + 32);
  }

  y += 60;

  if (data.wasteFootprint.breakdown.length > 0) {
    drawSubSectionHeader(doc, 'Waste Stream Breakdown', y, true);
    y += 10;

    const barData: BarChartItem[] = data.wasteFootprint.breakdown.map(item => ({
      name: item.stream,
      value: item.mass,
      color: item.color,
      maxValue: Math.max(...data.wasteFootprint!.breakdown.map(w => w.mass)),
    }));

    const barX = MARGIN + 50;
    barData.forEach((item, index) => {
      const wasteItem = data.wasteFootprint!.breakdown[index];

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(PASSPORT_COLORS.stone400);
      doc.text(item.name.substring(0, 12), MARGIN, y + 6);

      drawProgressBar(
        doc,
        item.value,
        item.maxValue!,
        barX,
        y,
        CONTENT_WIDTH - 110,
        8,
        item.color,
        PASSPORT_COLORS.stone700
      );

      doc.setFont('courier', 'normal');
      doc.setFontSize(8);
      doc.setTextColor('#FFFFFF');
      doc.text(`${item.value.toFixed(3)} ${wasteItem.unit}`, PAGE_WIDTH - MARGIN - 30, y + 6, { align: 'right' });

      if (wasteItem.recyclable) {
        doc.setTextColor(PASSPORT_COLORS.green400);
        doc.text('R', PAGE_WIDTH - MARGIN - 5, y + 6);
      } else {
        doc.setTextColor(PASSPORT_COLORS.red400);
        doc.text('X', PAGE_WIDTH - MARGIN - 5, y + 6);
      }

      y += 14;
    });
  }

  addPageFooter(doc, data.meta.date);
}

function drawLandUsePage(doc: jsPDF, data: PassportPDFData): void {
  if (!data.landUse) return;

  doc.setFillColor(PASSPORT_COLORS.stone900);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  let y = 30;
  y = drawSectionHeader(doc, '06', 'Land Use & Nature', y, true);

  y += 5;
  drawMetricCard(
    doc,
    MARGIN,
    y,
    CONTENT_WIDTH * 0.4,
    'Total Land Use',
    data.landUse.total.toFixed(2),
    data.landUse.unit,
    PASSPORT_COLORS.emerald400,
    true
  );

  y += 60;

  if (data.landUse.breakdown && data.landUse.breakdown.length > 0) {
    drawSubSectionHeader(doc, 'Material Land Footprint', y, true);
    y += 10;

    doc.setFont('courier', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(PASSPORT_COLORS.stone400);
    doc.text('MATERIAL', MARGIN, y);
    doc.text('ORIGIN', MARGIN + 55, y);
    doc.text('MASS', MARGIN + 100, y);
    doc.text('INTENSITY', MARGIN + 130, y);
    doc.text('FOOTPRINT', PAGE_WIDTH - MARGIN, y, { align: 'right' });

    doc.setDrawColor(PASSPORT_COLORS.stone700);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y + 4, PAGE_WIDTH - MARGIN, y + 4);

    y += 12;

    data.landUse.breakdown.slice(0, 10).forEach((item) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor('#FFFFFF');
      doc.text(item.material.substring(0, 20), MARGIN, y);

      doc.setTextColor(PASSPORT_COLORS.stone400);
      doc.text(item.origin?.substring(0, 12) || '-', MARGIN + 55, y);

      doc.setTextColor('#FFFFFF');
      doc.text(`${item.mass.toFixed(3)} kg`, MARGIN + 100, y);

      doc.setTextColor(PASSPORT_COLORS.stone400);
      doc.text(`${item.landIntensity.toFixed(2)}`, MARGIN + 130, y);

      doc.setTextColor(PASSPORT_COLORS.emerald400);
      doc.text(`${item.totalFootprint.toFixed(3)} ${item.unit}`, PAGE_WIDTH - MARGIN, y, { align: 'right' });

      y += 10;
    });
  }

  addPageFooter(doc, data.meta.date);
}

function drawConclusionPage(doc: jsPDF, data: PassportPDFData): void {
  doc.setFillColor(PASSPORT_COLORS.stone50);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  let y = PAGE_HEIGHT / 2 - 60;

  doc.setFont('times', 'normal');
  doc.setFontSize(28);
  doc.setTextColor(PASSPORT_COLORS.stone900);
  doc.text(data.conclusion.title, PAGE_WIDTH / 2, y, { align: 'center' });

  y += 20;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(PASSPORT_COLORS.stone600);
  const conclusionLines = doc.splitTextToSize(data.conclusion.content, CONTENT_WIDTH - 40);
  doc.text(conclusionLines, PAGE_WIDTH / 2, y, { align: 'center', maxWidth: CONTENT_WIDTH - 40 });

  y += conclusionLines.length * 5 + 30;

  if (data.passportUrl) {
    drawCard(doc, (PAGE_WIDTH - 140) / 2, y, 140, 50, false);

    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(PASSPORT_COLORS.stone500);
    doc.text('VIEW FULL DIGITAL PASSPORT', PAGE_WIDTH / 2, y + 15, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(PASSPORT_COLORS.lime700);
    doc.text(data.passportUrl, PAGE_WIDTH / 2, y + 35, { align: 'center' });
  }

  y = PAGE_HEIGHT - 60;

  doc.setDrawColor(PASSPORT_COLORS.stone200);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);

  y += 15;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text('Generated by', MARGIN, y);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(PASSPORT_COLORS.stone600);
  doc.text('Alkatera', MARGIN + 28, y);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text('Platform', MARGIN + 45, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(PASSPORT_COLORS.stone400);
  doc.text('ISO 14040/44 Compliant  |  Verified Data', PAGE_WIDTH - MARGIN, y, { align: 'right' });

  addPageFooter(doc, data.meta.date);
}

export async function generatePassportPDF(data: PassportPDFData): Promise<jsPDF> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  currentPageNumber = 1;

  drawCoverPage(doc, data);

  addNewPage(doc, data.meta.date);
  drawExecutiveSummaryPage(doc, data);

  addNewPage(doc, data.meta.date);
  drawMethodologyPage(doc, data);

  addNewPage(doc, data.meta.date);
  drawClimateImpactPage(doc, data);

  if (data.waterFootprint) {
    addNewPage(doc, data.meta.date);
    drawWaterFootprintPage(doc, data);
  }

  if (data.wasteFootprint) {
    addNewPage(doc, data.meta.date);
    drawWasteFootprintPage(doc, data);
  }

  if (data.landUse && data.landUse.total > 0) {
    addNewPage(doc, data.meta.date);
    drawLandUsePage(doc, data);
  }

  addNewPage(doc, data.meta.date);
  drawConclusionPage(doc, data);

  return doc;
}

export function downloadPassportPDF(data: PassportPDFData, filename?: string): void {
  generatePassportPDF(data).then((doc) => {
    const name = filename || `${data.meta.productName.replace(/\s+/g, '_')}_LCA_Report.pdf`;
    doc.save(name);
  });
}
