"use client";

import { cn } from "@/lib/utils";
import type { PageWrapperProps, SectionHeaderProps } from "./types";

export const PageWrapper = ({
  children,
  className,
  theme = 'light',
  pageNumber
}: PageWrapperProps) => {
  const isDark = theme === 'dark';

  return (
    <div className="w-[794px] h-[1123px] relative mx-auto my-8 bg-white shadow-xl overflow-hidden print:shadow-none print:m-0 print:break-after-page">
      <div
        className={cn(
          "w-full h-full flex flex-col p-12 relative",
          isDark ? "bg-[#1c1917] text-white" : "bg-[#f5f5f4] text-neutral-900",
          className
        )}
      >
        {children}

        <div className="absolute bottom-12 left-12 right-12 flex justify-between items-end text-[10px] font-mono opacity-40 uppercase tracking-widest border-t border-current pt-4">
          <div className="flex gap-8">
            <span>Generated by</span>
            <span className="font-bold">AlkaTera</span>
            <span>Platform</span>
          </div>
          {pageNumber && <div className="font-bold text-sm">{pageNumber}</div>}
          <div className="text-right">ISO 14040/44 Compliant | {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
        </div>
      </div>
    </div>
  );
};

export const SectionHeader = ({
  number,
  title,
  theme = 'light',
  className
}: SectionHeaderProps) => {
  return (
    <div className={cn(
      "flex items-baseline gap-4 mb-16 border-b pb-4",
      theme === 'dark' ? "border-white/20" : "border-black/10",
      className
    )}>
      <span className="text-[#ccff00] font-mono text-sm font-bold tracking-widest">{number}</span>
      <h2 className="text-4xl font-serif font-light">{title}</h2>
    </div>
  );
};
