/**
 * THE NUMBERS-DON'T-CHANGE HARNESS
 *
 * Sibling to `packaging-parametric-golden.test.ts`, one level up: that file
 * locks the pure packaging factor maths, this one locks the whole aggregation
 * that turns resolved materials into the `aggregated_impacts` a customer reads
 * off their LCA report.
 *
 * Its job is the `main` → `redesign` cutover. That move changes the app, the
 * host and the schema simultaneously, and redesign has rewritten a large part
 * of `product-lca-aggregator.ts` — most notably lifting distribution, use phase
 * and end of life out into `lib/lca/downstream-stages.ts` and computing them
 * BEFORE the product-loss block rather than after. The comment there says the
 * code moved "verbatim". This test is how that claim gets checked instead of
 * believed.
 *
 * HOW TO USE IT AT CUTOVER
 * Copy these three files onto `redesign` unchanged:
 *   lib/__tests__/lca-aggregator-golden.test.ts   (this file)
 *   lib/__tests__/fixtures/lca-golden-cases.ts
 *   lib/__tests__/support/aggregator-harness.ts
 * Run it. Every expected value below is a number `main` produces today. If
 * redesign reproduces them, the engine is safe to cut over. If a value moves,
 * the diff between the two branches is the cause and the delta is exactly what
 * every customer's footprint would shift by.
 *
 * The numbers are deliberately written out in full rather than snapshotted.
 * A snapshot file can be regenerated by a tired person at 6pm; a literal has
 * to be edited on purpose.
 */
import { describe, it, expect, vi } from 'vitest';

// `calculateTransportEmissions` constructs its own client from the browser
// singleton, so distribution can only be exercised by stubbing that module.
// The stub serves emission-factor ROWS only — all the transport arithmetic
// remains real. See the note in aggregator-harness.ts.
vi.mock('@/lib/supabase/browser-client', async () => {
  const { createEmissionFactorStub } = await import('./support/aggregator-harness');
  return { getSupabaseBrowserClient: () => createEmissionFactorStub() };
});

import { aggregateProductImpacts } from '@/lib/product-lca-aggregator';
import { createAggregatorStub } from './support/aggregator-harness';
import { GOLDEN_CASES, FACILITY_EMISSIONS, PCF_ID, type GoldenCase } from './fixtures/lca-golden-cases';

/** Tight enough that a real methodology change fails; loose enough to survive float noise. */
const PRECISION = 9;

async function runCase(name: string) {
  const testCase = GOLDEN_CASES.find((c) => c.name === name) as GoldenCase;
  if (!testCase) throw new Error(`No golden case named "${name}"`);

  const stub = createAggregatorStub(testCase.fixture);
  const result = await aggregateProductImpacts(
    stub.client,
    PCF_ID,
    FACILITY_EMISSIONS as any,
    testCase.boundary,
    testCase.usePhaseConfig,
    testCase.eolConfig,
    testCase.distributionConfig,
    testCase.productLossConfig,
  );

  expect(result.success).toBe(true);
  return {
    total: result.total_carbon_footprint,
    stages: (result.impacts as any).breakdown.by_lifecycle_stage,
    scopes: (result.impacts as any).breakdown.by_scope,
    stub,
  };
}

describe('golden: cradle-to-gate (upstream only)', () => {
  it('reproduces the locked total and stage split', async () => {
    const { total, stages } = await runCase('gate');

    expect(total).toBeCloseTo(0.4599576, PRECISION);
    expect(stages.raw_materials).toBeCloseTo(0.282, PRECISION);
    expect(stages.packaging).toBeCloseTo(0.17795, PRECISION);
    expect(stages.processing).toBeCloseTo(0.0000076, PRECISION);

    // A gate study must carry no downstream burden whatsoever.
    expect(stages.distribution).toBe(0);
    expect(stages.use_phase).toBe(0);
    expect(stages.end_of_life).toBe(0);
  });
});

describe('golden: cradle-to-grave (the full downstream chain)', () => {
  it('reproduces the locked total and every downstream stage', async () => {
    const { total, stages, scopes } = await runCase('grave');

    expect(total).toBeCloseTo(0.5012367866666667, PRECISION);
    // 0.93 kg over 360 truck-km at the fixtured DEFRA HGV factor.
    expect(stages.distribution).toBeCloseTo(0.035987, PRECISION);
    expect(stages.use_phase).toBeCloseTo(0.0035935200000000002, PRECISION);
    expect(stages.end_of_life).toBeCloseTo(0.001698666666666667, PRECISION);

    // Upstream is untouched by extending the boundary.
    expect(stages.raw_materials).toBeCloseTo(0.282, PRECISION);
    expect(stages.packaging).toBeCloseTo(0.17795, PRECISION);

    // Facility emissions stay in scopes 1 and 2; everything else is scope 3.
    expect(scopes.scope1).toBeCloseTo(0.0000027583333333333333, PRECISION);
    expect(scopes.scope2).toBeCloseTo(0.000004841666666666666, PRECISION);
    expect(scopes.scope3).toBeCloseTo(0.5012291866666667, PRECISION);
  });

  it('the stage split sums to the reported total', async () => {
    const { total, stages } = await runCase('grave');
    const summed = Object.values(stages as Record<string, number>).reduce((a, b) => a + b, 0);
    expect(summed).toBeCloseTo(total, PRECISION);
  });
});

describe('golden: cradle-to-shelf keeps RETAIL refrigeration', () => {
  it('includes retail chilling but not the consumer share, and no end of life', async () => {
    const { total, stages } = await runCase('shelf_chilled');

    expect(total).toBeCloseTo(0.49824851000000003, PRECISION);
    expect(stages.distribution).toBeCloseTo(0.035987, PRECISION);
    expect(stages.end_of_life).toBe(0);

    // The load-bearing assertion. A shelf-boundary study excludes the use
    // phase as a concept, but retail chilled storage happens BEFORE the
    // consumer buys, so it must still be counted. This is the branch most
    // likely to be lost in a refactor, and its absence would look like a
    // plausible small number rather than an obvious zero.
    expect(stages.use_phase).toBeCloseTo(0.00230391, PRECISION);
    expect(stages.use_phase).toBeGreaterThan(0);

    // It must be strictly the retail share — smaller than the full use phase
    // that the grave case books.
    const grave = await runCase('grave');
    expect(stages.use_phase).toBeLessThan(grave.stages.use_phase);
  });
});

describe('golden: product loss scales upstream ONLY', () => {
  it('reproduces the locked total with a loss multiplier applied', async () => {
    const { total, stages } = await runCase('grave_with_loss');

    expect(total).toBeCloseTo(0.5506058169389602, PRECISION);
    expect(stages.raw_materials).toBeCloseTo(0.3122681519705007, PRECISION);
    expect(stages.packaging).toBeCloseTo(0.19705006256436383, PRECISION);
  });

  it('pins the stage ORDERING that redesign inverted', async () => {
    // redesign computes the downstream stages before the loss block; main
    // computed them after. The refactor is only safe because the loss block
    // scales scalar running totals and never touches `materials`. That
    // invariant is what this asserts: 2% distribution + 3% retail + 5%
    // consumer loss => 1/(0.98 x 0.97 x 0.95) = 1.1073352... applied to
    // upstream, and applied to downstream NOT AT ALL.
    const withLoss = await runCase('grave_with_loss');
    const withoutLoss = await runCase('grave');
    const expectedMultiplier = 1 / (0.98 * 0.97 * 0.95);

    expect(withLoss.stages.raw_materials / withoutLoss.stages.raw_materials).toBeCloseTo(
      expectedMultiplier,
      PRECISION,
    );
    expect(withLoss.stages.packaging / withoutLoss.stages.packaging).toBeCloseTo(
      expectedMultiplier,
      PRECISION,
    );

    // Downstream stages are per-unit-delivered already, so scaling them too
    // would double-count the loss.
    expect(withLoss.stages.distribution).toBeCloseTo(withoutLoss.stages.distribution, PRECISION);
    expect(withLoss.stages.use_phase).toBeCloseTo(withoutLoss.stages.use_phase, PRECISION);
    expect(withLoss.stages.end_of_life).toBeCloseTo(withoutLoss.stages.end_of_life, PRECISION);
  });
});

describe('golden: what actually gets persisted', () => {
  it('writes the same impacts it returns, and completes the PCF', async () => {
    const { total, stub } = await runCase('grave');

    // The report reads the STORED row, not the return value, so the thing
    // worth locking is what would land in the database.
    const persisted = stub.persistedImpacts();
    expect(persisted).toBeDefined();
    expect(persisted!.climate_change_gwp100).toBeCloseTo(total, PRECISION);

    const completion = stub.writes.find(
      (w) => w.table === 'product_carbon_footprints' && w.payload.status === 'completed',
    );
    expect(completion).toBeDefined();
    expect(completion!.payload.per_unit_emissions_verified).toBe(true);
    // 500 ml normalised to litres for the per-unit check.
    expect(completion!.payload.bulk_volume_per_functional_unit).toBeCloseTo(0.5, PRECISION);

    // The previous active PCF must be superseded before this one completes,
    // or the partial unique index rejects the write.
    const supersede = stub.writes.find(
      (w) => w.table === 'product_carbon_footprints' && w.payload.status === 'superseded',
    );
    expect(supersede).toBeDefined();
    expect(stub.writes.indexOf(supersede!)).toBeLessThan(stub.writes.indexOf(completion!));
  });
});

describe('golden: determinism', () => {
  it('two identical runs agree to the last bit', async () => {
    const first = await runCase('grave_with_loss');
    const second = await runCase('grave_with_loss');
    expect(first.total).toBe(second.total);
    expect(first.stages).toEqual(second.stages);
  });
});
