/*
  # Create OpenLCA Process Cache Table

  ## Overview
  This migration creates a cache table for storing OpenLCA API responses to improve
  performance and reduce API costs.

  ## New Tables
  - `openlca_process_cache` - Caches OpenLCA API search results

  ## Security
  - No RLS policies needed - cache is shared across all authenticated users

  ## Performance
  - Unique index on search_term for instant cache hit detection
  - Index on created_at for efficient TTL-based cleanup
*/

-- Create the OpenLCA process cache table
CREATE TABLE IF NOT EXISTS public.openlca_process_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_term text NOT NULL,
  results jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create unique index on search_term for instant cache lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_openlca_cache_search_term
  ON public.openlca_process_cache(search_term);

-- Create index on created_at for efficient cleanup queries
CREATE INDEX IF NOT EXISTS idx_openlca_cache_created_at
  ON public.openlca_process_cache(created_at DESC);

-- Create function to automatically clean up stale cache entries
CREATE OR REPLACE FUNCTION public.cleanup_openlca_cache()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.openlca_process_cache
  WHERE created_at < (now() - interval '24 hours');
END;
$$;

-- Grant necessary permissions
GRANT SELECT, INSERT, DELETE ON public.openlca_process_cache TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_openlca_cache() TO authenticated;