/*
  # Create OpenLCA Process Cache Table

  ## Overview
  This migration creates a cache table for storing OpenLCA API responses to improve
  performance and reduce API costs. The cache automatically manages entries and provides
  fast lookups for repeated searches.

  ## New Tables

  ### `openlca_process_cache`
  Caches responses from the OpenLCA API for improved performance.

  **Columns:**
  - `id` (bigint, primary key) - Unique identifier for cache entries
  - `search_term` (text, unique, not null) - The search query used (case-insensitive)
  - `results` (jsonb, not null) - Array of process results from OpenLCA API
  - `created_at` (timestamptz, not null) - Cache entry timestamp for TTL management

  ## Security
  - No RLS policies needed - cache is shared across all authenticated users
  - Edge functions handle cache read/write operations
  - Stale entries (>24h) are automatically purged

  ## Performance
  - Unique index on search_term for instant cache hit detection
  - Index on created_at for efficient TTL-based cleanup
  - JSONB storage for flexible result structures

  ## Notes
  - Cache TTL is 24 hours
  - Results are sanitized before caching: {id, name, category}
  - Search terms are normalized (trimmed, lowercased) for consistency
*/

-- Create the OpenLCA process cache table
CREATE TABLE IF NOT EXISTS public.openlca_process_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_term text NOT NULL,
  results jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.openlca_process_cache IS 'Caches responses from the OpenLCA API to improve performance and reduce external API costs. Entries expire after 24 hours.';
COMMENT ON COLUMN public.openlca_process_cache.search_term IS 'Normalized search query (trimmed, lowercased) used as cache key.';
COMMENT ON COLUMN public.openlca_process_cache.results IS 'Array of sanitized process objects: [{id, name, category}] from OpenLCA API response.';
COMMENT ON COLUMN public.openlca_process_cache.created_at IS 'Cache entry timestamp for TTL-based expiration (24 hour lifetime).';

-- Create unique index on search_term for instant cache lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_openlca_cache_search_term
  ON public.openlca_process_cache(search_term);

-- Create index on created_at for efficient cleanup queries
CREATE INDEX IF NOT EXISTS idx_openlca_cache_created_at
  ON public.openlca_process_cache(created_at DESC);

-- Create function to automatically clean up stale cache entries
CREATE OR REPLACE FUNCTION public.cleanup_openlca_cache()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Delete cache entries older than 24 hours
  DELETE FROM public.openlca_process_cache
  WHERE created_at < (now() - interval '24 hours');
END;
$$;

COMMENT ON FUNCTION public.cleanup_openlca_cache() IS 'Removes OpenLCA cache entries older than 24 hours to maintain freshness and manage storage.';

-- Grant necessary permissions
GRANT SELECT, INSERT, DELETE ON public.openlca_process_cache TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_openlca_cache() TO authenticated;
