/*
  # Populate Beverage Industry Proxy Mappings

  Inserts industry-standard emission factors for common beverage categories
  when manufacturer-specific data is unavailable.

  Data sources:
  - Ecoinvent 3.12 database (global averages)
  - LCA Food Database
  - Industry benchmarking studies

  Note: Values are conservative estimates representing global averages
*/

-- Insert proxy mappings for beverage categories
INSERT INTO product_category_proxy_mappings (
  product_category,
  product_subcategory,
  ecoinvent_process_name,
  ecoinvent_version,
  co2e_per_kg,
  ghg_fossil_co2e_per_kg,
  co2_per_kg,
  ch4_per_kg,
  n2o_per_kg,
  water_use_per_kg,
  data_quality_score,
  geographical_scope,
  temporal_scope,
  technology_scope,
  confidence_level,
  description,
  source_reference,
  recommended_buffer_percentage
) VALUES
  -- Spirits
  (
    'Spirits',
    'Gin',
    'Spirit production, global average',
    '3.12',
    2.8,  -- kg CO2e per kg product
    2.65,
    2.50,
    0.008,
    0.005,
    15.0, -- litres water per kg
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for distilled spirits production including energy for distillation, bottling, and packaging',
    'Ecoinvent 3.12: Ethanol production, fermentation and distillation',
    10.0
  ),
  (
    'Spirits',
    'Vodka',
    'Spirit production, global average',
    '3.12',
    2.6,
    2.45,
    2.30,
    0.007,
    0.005,
    12.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for distilled spirits production, vodka typically has slightly lower emissions than gin due to fewer botanicals',
    'Ecoinvent 3.12: Ethanol production, fermentation and distillation',
    10.0
  ),
  (
    'Spirits',
    'Rum',
    'Spirit production, global average',
    '3.12',
    2.9,
    2.70,
    2.55,
    0.008,
    0.006,
    14.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for rum production from molasses or sugarcane',
    'Ecoinvent 3.12: Ethanol production, fermentation and distillation',
    10.0
  ),
  (
    'Spirits',
    'Whisky',
    'Spirit production, global average',
    '3.12',
    3.2,
    3.00,
    2.85,
    0.009,
    0.006,
    18.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for whisky production including malting, fermentation, distillation, and maturation energy',
    'Ecoinvent 3.12: Ethanol production with malting process',
    10.0
  ),

  -- Beer & Cider
  (
    'Beer',
    'Lager',
    'Beer production, global average',
    '3.12',
    0.85,
    0.78,
    0.72,
    0.003,
    0.002,
    8.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for lager production including brewing, fermentation, and packaging',
    'Ecoinvent 3.12: Beer production, brewery',
    10.0
  ),
  (
    'Beer',
    'Ale',
    'Beer production, global average',
    '3.12',
    0.88,
    0.81,
    0.75,
    0.003,
    0.002,
    8.5,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for ale production, slightly higher than lager due to warmer fermentation',
    'Ecoinvent 3.12: Beer production, brewery',
    10.0
  ),
  (
    'Cider',
    NULL,
    'Cider production, global average',
    '3.12',
    0.75,
    0.68,
    0.63,
    0.003,
    0.002,
    6.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for cider production from apple juice fermentation',
    'Ecoinvent 3.12: Cider production, fermentation',
    10.0
  ),

  -- Soft Drinks
  (
    'Soft Drink',
    'Carbonated',
    'Soft drink production, carbonated',
    '3.12',
    0.45,
    0.42,
    0.39,
    0.002,
    0.001,
    3.5,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for carbonated soft drink production including syrup preparation, carbonation, and packaging',
    'Ecoinvent 3.12: Soft drink production, carbonated',
    10.0
  ),
  (
    'Soft Drink',
    'Still',
    'Soft drink production, non-carbonated',
    '3.12',
    0.38,
    0.35,
    0.33,
    0.001,
    0.001,
    3.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for non-carbonated beverage production',
    'Ecoinvent 3.12: Soft drink production',
    10.0
  ),
  (
    'Juice',
    NULL,
    'Juice production, global average',
    '3.12',
    0.65,
    0.60,
    0.56,
    0.002,
    0.002,
    4.5,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for juice production including pressing, pasteurisation, and packaging',
    'Ecoinvent 3.12: Juice production from concentrate',
    10.0
  ),

  -- Water
  (
    'Water',
    'Still',
    'Bottled water production',
    '3.12',
    0.25,
    0.23,
    0.22,
    0.001,
    0.0005,
    2.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for bottled water production including filtration, bottling, and packaging',
    'Ecoinvent 3.12: Tap water, at user',
    10.0
  ),
  (
    'Water',
    'Sparkling',
    'Bottled sparkling water production',
    '3.12',
    0.32,
    0.29,
    0.27,
    0.001,
    0.001,
    2.2,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for sparkling water production including carbonation',
    'Ecoinvent 3.12: Tap water with carbonation',
    10.0
  ),

  -- Wine
  (
    'Wine',
    'Red',
    'Wine production, red',
    '3.12',
    1.15,
    1.05,
    0.98,
    0.004,
    0.003,
    5.5,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for red wine production including fermentation, aging, and bottling',
    'Ecoinvent 3.12: Wine production from grapes',
    10.0
  ),
  (
    'Wine',
    'White',
    'Wine production, white',
    '3.12',
    1.08,
    0.98,
    0.92,
    0.004,
    0.002,
    5.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for white wine production',
    'Ecoinvent 3.12: Wine production from grapes',
    10.0
  ),
  (
    'Wine',
    'Rosé',
    'Wine production, rosé',
    '3.12',
    1.10,
    1.00,
    0.94,
    0.004,
    0.003,
    5.2,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for rosé wine production',
    'Ecoinvent 3.12: Wine production from grapes',
    10.0
  ),

  -- RTD/Premix
  (
    'Ready-to-Drink',
    'Spirit-based',
    'RTD alcoholic beverage production',
    '3.12',
    1.20,
    1.10,
    1.02,
    0.004,
    0.003,
    7.0,
    'Low',
    'Global',
    '2020-2025',
    'Mixed technology',
    'Estimated',
    'Global average for ready-to-drink alcoholic beverage production',
    'Ecoinvent 3.12: Mixed alcoholic beverage production',
    10.0
  )

ON CONFLICT DO NOTHING;
