-- Filename-keyed document profiles for the Smart Upload learning loop.
--
-- Spreadsheets rarely carry a supplier name, so type corrections are
-- remembered against a normalised filename signature (lib/ingest/
-- doc-signature.ts) instead of a supplier key. match_kind distinguishes the
-- two keyspaces sharing the supplier_key column, and joins the unique
-- constraint so a filename pattern can never merge with a real supplier name.

alter table public.ingest_document_profiles
  add column if not exists match_kind text not null default 'supplier'
    check (match_kind in ('supplier', 'filename'));

comment on column public.ingest_document_profiles.match_kind is
  'supplier: supplier_key is a normalised supplier name. filename: supplier_key is a docSignature() filename pattern learned from a type correction.';

-- Widen the unique constraint to include match_kind. The autogenerated name
-- comes from the original `unique (organization_id, supplier_key, result_type)`.
alter table public.ingest_document_profiles
  drop constraint if exists ingest_document_profiles_organization_id_supplier_key_resul_key;

alter table public.ingest_document_profiles
  add constraint ingest_document_profiles_org_kind_key_type_uidx
    unique (organization_id, match_kind, supplier_key, result_type);
