"use client";

import Link from 'next/link';
import { BookOpen, ArrowRight } from 'lucide-react';
import type { LCADataConclusion, LCADataMeta, TierVisibility } from '@/lib/types/passport';

interface ConclusionSectionProps {
  data: LCADataConclusion;
  meta: LCADataMeta;
  visibility: TierVisibility;
  onDownloadPDF?: () => void;
  onShare?: () => void;
}

export default function ConclusionSection({
  data,
  meta,
  visibility,
  onDownloadPDF,
  onShare,
}: ConclusionSectionProps) {
  const handleShare = async () => {
    if (onShare) {
      onShare();
      return;
    }

    if (typeof navigator !== 'undefined' && navigator.share) {
      try {
        await navigator.share({
          title: `${meta.productName} - Product Passport`,
          text: `View the environmental impact data for ${meta.productName}`,
          url: window.location.href,
        });
      } catch {
        navigator.clipboard?.writeText(window.location.href);
      }
    } else {
      navigator.clipboard?.writeText(window.location.href);
    }
  };

  return (
    <section className="py-24 px-6 md:px-12 max-w-4xl mx-auto text-center bg-stone-50">
      <h2 className="font-serif text-4xl md:text-5xl mb-8 text-stone-900">
        {data.title}
      </h2>
      <p className="text-stone-600 leading-relaxed text-lg max-w-2xl mx-auto mb-12">
        {data.content}
      </p>

      {visibility.showMethodologyLink && meta.methodologyPageUrl && (
        <div className="mb-12 p-6 bg-white rounded-xl border border-stone-200 max-w-xl mx-auto">
          <div className="flex items-center justify-center gap-3 mb-3">
            <BookOpen className="w-5 h-5 text-lime-600" />
            <h3 className="font-mono text-xs uppercase tracking-widest text-stone-500">
              Technical Documentation
            </h3>
          </div>
          <p className="text-sm text-stone-600 mb-4">
            Learn more about the standards, tools, and methodology used to calculate this LCA.
          </p>
          <Link
            href={meta.methodologyPageUrl}
            className="inline-flex items-center gap-2 text-lime-700 hover:text-lime-800 font-medium transition-colors"
          >
            <span>View Full Methodology</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      )}

      <div className="flex flex-col md:flex-row justify-center gap-6">
        {visibility.showDownloadPDF && (
          <button
            onClick={onDownloadPDF}
            className="bg-stone-900 text-white px-8 py-4 font-mono text-xs uppercase tracking-widest hover:bg-brand-accent hover:text-black transition-colors duration-300"
          >
            Download Full PDF
          </button>
        )}
        <button
          onClick={handleShare}
          className="bg-white border border-stone-200 text-stone-900 px-8 py-4 font-mono text-xs uppercase tracking-widest hover:bg-stone-50 transition-colors duration-300"
        >
          Share Report
        </button>
      </div>

      <div className="mt-24 pt-8 border-t border-stone-200 flex flex-col md:flex-row justify-between items-center text-xs font-mono text-stone-400">
        <span>
          Generated by{' '}
          <span className="font-semibold text-stone-600">Alkatera</span> Platform
        </span>
        <div className="flex gap-4 mt-4 md:mt-0">
          <span>ISO 14040/44 Compliant</span>
          <span>Verified Data</span>
        </div>
      </div>
    </section>
  );
}
